### ISSUE TITLE
I want to see the prices (ranges) in the category page So I know how much do I need to pay for the product

### ISSUE THREAD

**Issue by rmakara** [vuestorefront/shopware-pwa#10]
**Context**
Products in category page will appear in some product boxes. Each box may be associated with a single product or with many variants. I want to see specific price of the product or a range if different variants have different prices.

**Dependencies**
* Blocked by #4 
* Blocked by #7 
* Blocked by #1076 

**Acceptance criteria**
* I can see the price of a single product.
* I can see price minimum if variants have different prices.
* I can see price maximum if variants have different prices.
* I can see price minimum if price is dependent on some rules, that should be shown in a range in the category page.
* I can see price minimum if price is dependent on some rules, that should be shown in a range in the category page.

blocked by https://github.com/DivanteLtd/storefront-ui/issues/1401

**Comment by patzick** [comment]
this is project related and will not be implemented for now in core
