### ISSUE TITLE
[BUG] Default language route redirect

### ISSUE THREAD

**Issue by fsavina** [vuestorefront/shopware-pwa#1008]
### Describe the bug
If the current route contains the default locale, the I18n middleware forces a redirection to the same route removing the locale from the url.
This behaviour should be optional in case you want to preserve the locale in the routes also for the default language.

### Steps to reproduce
Access the following page:
https://shopware-pwa.storefrontcloud.io/en-GB/

you'll be redirected to 
https://shopware-pwa.storefrontcloud.io/

**Comment by patzick** [comment]
As marked in Sprint 44 - this issue should be completed by now. Closing, please let us know if this bug still occurs
