### ISSUE TITLE
[BUG] Missing details on paid order

### ISSUE THREAD

**Issue by fsavina** [vuestorefront/shopware-pwa#1113]
Once a order has been paid the `SwOrderDetails` component is unable to retrieve the info about the payment method nor the shipping method because `getOrderPaymentMethodId` returns an `undefined` value here:

https://github.com/DivanteLtd/shopware-pwa/blob/5e545af082ec2f9c22acc2335a186d08e3e81bd5/packages/default-theme/components/SwOrderDetails.vue#L164

**Comment by fsavina** [comment]
same problem when the payment fails

**Comment by mkucmus** [comment]
@fsavina please add some more details in every issue like version of shopware-pwa, version of Shopware 6 and will be easier to reproduce the issue :+1:

**Comment by fsavina** [comment]
shopware-pwa version: canary
SW version: v6.3.0.2

**Comment by mkucmus** [comment]
TODO:
- refactor components/SwOrderDetails.vue to have no additional requests for getting the payment and shipping method details
- on success page - perform a redirection to the payment gateway automatically (if external URL is available).
