### ISSUE TITLE
[BUG] Linting/formatting of vue components

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/shopware-pwa#1136]
### Describe the bug
Besides being set up as git hook, the formatting doesn't seem to be applied. All vue components in default-theme are not formatted according to prettierrc. For example there are double quotes everywhere besides single quotes being configured in prettierrc.

It's just a small issue, but it's a bit annoying because IF you have setup formatting/linting in your IDE every overridden component gets formatted according to prettierrc. That does make updating/comparing overridden components to their original more difficult than it needs to be, because you get all these formatting differences.

I like to propose, that all components get formatted according to prettierrc, alternatively the configuration of prettier should at least match the current formatting style.

### Additional context
https://github.com/DivanteLtd/shopware-pwa/blob/master/packages/default-theme/.prettierrc

**Comment by patzick** [comment]
I think this one is already done, @niklaswolf can you confirm?

**Comment by niklaswolf** [comment]
@patzick I think the prettier config in the project template caused the issue, because it had other configurations than the one in default-theme
