### ISSUE TITLE
[BUG] Override unstable

### ISSUE THREAD

**Issue by abvdveen** [vuestorefront/shopware-pwa#1143]
Using shopware-pwa override copies the file, for instance <projectFolder>/.shopware-pwa/source/components/SwFooter.vue correctly to <projectFolder>/src/components/SwFooter.vue.

But when I then edit the latter, you'll always see a rebuild of the client and server in the shell running shopware-pwa dev, but the file in .shopware-pwa/source/components is not always updated. Most of the time it is replaced by an empty file, sometimes it gets updated. How can I debug the hot rebuild process to find the cause?

**Comment by niklaswolf** [comment]
I also see this behaviour, even if I only do some really small changes, for example adding a CSS class. When I refresh the site, I always get the following error: `render function or template not defined in component`. That's because the file in .shopware-pwa/source/components is empty as @abvdveen describes it.

**Comment by niklaswolf** [comment]
Maybe this has something to do with chokidar. https://github.com/DivanteLtd/shopware-pwa/blob/master/packages/nuxt-module/src/module.ts#L234 
As I'm developing inside a docker container I recall many issues regarding chokidar not picking up file changes correctly when using volume mounts. The workaround for this apparently is to configure chokidar to use polling (`CHOKIDAR_USEPOLLING=1 yarn dev`). I'll try that and will report back.

**Comment by niklaswolf** [comment]
After some days using this workaround, I can say that it's MUCH more stable, in fact I did not have any errors while using it.

**Comment by abvdveen** [comment]
@niklaswolf Thanks for the tip! Encountered the same error on the Hypernode platform and using CHOKIDAR_USEPOLLING=1 yarn dev seems to fix it.
