### ISSUE TITLE
getNavigation from @shopware-pwa/shopware-6-client calls custom Endpoint with limited customization

### ISSUE THREAD

**Issue by krasej** [vuestorefront/shopware-pwa#1160]
For example the file CmsElementCategoryNavigation uses getNavigation from @shopware-pwa/shopware-6-client. The Endpoint called is the custom Endpoint /store-api/v3/pwa/navigation. This endpoint only accepts the parameters rootnode and depth. Since both parameters are supported by the store-api natively it should be called instead. This will make these requests configurabl.

**Comment by mkucmus** [comment]
The issue is outdated since the application has been using the core's built-in navigation endpoint as a part of store-api.
