### ISSUE TITLE
[FEATURE] docker-compose definition for dev purposes

### ISSUE THREAD

**Issue by mkucmus** [vuestorefront/shopware-pwa#1178]
### Description
we can standardize the development environment by providing containerization. we can utilize the most popular solution - docker & docker-compose stack

### Acceptance criteria
- [ ] docker-compose.dev.yml is created
- [ ] the yml contains the definition of the container (inspidered by https://github.com/shopware/development)
- [ ] the showpare API related images can be versioned and froze at some version (configurable from .env, for instance)
- [ ] the shopware API image has included and activated https://github.com/elkmod/SwagShopwarePwa plugin
- [ ] the second thing is to have shopware-pwa container, built on specific node version (configurable from .env as well)
- [ ] the shopware-pwa should have mapped files locally to have a possibility of hot replacement after local files are changed
- [ ] the shopware-pwa container uses mapped shopware-pwa.config.js which points to the shopware api container address

**Comment by patzick** [comment]
this should be covered by dockware, closing
