### ISSUE TITLE
[BUG] Add-to-cart success notification even if error occured

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/shopware-pwa#1217]
### Describe the bug
Currently the success notification is displayed every time one adds something to the cart, even if the API returns an error.
I came across this when adding products that don't have enough stock (stock < wished quantity).

- set product to "sale" (german name: "Abverkauf") in shopware backend
- add available quantity to the cart --> always success, which is correct
- add one more item to the cart --> success message, but API returns error (out of stock)

**Comment by patzick** [comment]
Hey @niklas-wolf  - this one might be related to #1372, could you confirm that?

**Comment by niklaswolf** [comment]
@patzick yes certainly! It's the same place, see
https://github.com/vuestorefront/shopware-pwa/blob/master/packages/composables/src/logic/useAddToCart.ts#L86
The success-notification is broadcasted not taking the result of the api-call into account. This is also where the errors mentioned in #1372 would be received :)

**Comment by mkucmus** [comment]
hurray! finally we take care of errors object hidden in the 200 code's responses :) now we broadcast notices, warnings as same as errors. related PR is: #1422

**Comment by niklaswolf** [comment]
@mkucmus @patzick  great, that's a great improvement.
But this issue is still open with these changes I think, because the Success-Notification still gets broadcasted in useAddToCart even if there was an error in the response.

**Comment by niklaswolf** [comment]
I currently can not go on with this because the API seems broken when forcing an error (e.g. product out of stock)
https://issues.shopware.com/issues/NEXT-14960

**Comment by niklaswolf** [comment]
Shopware 6.4.2.1
Shopware-pwa 0.9.x

- If I add more than is available, but there was still something available (e.g. available stock: 1, added: 2) I get a warning that only X is available and it adds the available quantity to the cart. This is totally fine in my view ✅ 
- when nothing is available anymore, I still get only the success-notification, which is wrong. Expected would be an error message ❌
