### ISSUE TITLE
[BUG] Hydration error after update from 0.5.0 to canary

### ISSUE THREAD

**Issue by Chades** [vuestorefront/shopware-pwa#1256]
### Describe the bug
After I updated from **0.5.0** to **canary** with changing the version in **package.json** and running **yarn install**.
I run **npx @shopware-pwa/cli init** and start the project I get the following problem:
` ERROR  [UseSessionContext][refreshSessionContext] {                                                                                                                                                                              
  message: 'Internal server error',
  statusCode: 500
}`

And on the front-end this warning:
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside `<p>`, or missing `<tbody>`. Bailing hydration and performing full client-side render.

However if I use a nuxt-link on the rendered page (which is missing server-side context now), it loads the next page correctly.
Refreshing the page also ends with the same error.
If I revert back to **0.5.0** and run **npx @shopware-pwa/cli init** then it works again.
I am changing in **package.json** the version and run yarn isntall 
Am I missing something?

**Comment by mkucmus** [comment]
hi @Chades, thanks for reporting it! 
I'm aware of that and that error (`{ message: 'Internal server error', statusCode: 500 }`) comes from API and it's related to some issues with a shopware instance itself, the canary is connected to this by default (see shopware-pwa.config.js in your initiated project)

If you set your shopware-pwa with our shopware6-demo instance or something own, you have no errors there :+1:

the frontend warning is something worth checking, I will find out what's happening there :)

**Comment by Chades** [comment]
Hi @mkucmus, we are already on our own Shopware instance.
We have only installed the PWA Integration plugin which is on **dev-master** version and the instance is on **v6.3.3.0**

Regarding the front-end warning,a s the warning already says, it renders only on client-side if I open the page or I press refresh page. Clicking on nuxt-link the page renders correctly, everytime I press refresh, I get the same errors as above.

**Comment by patzick** [comment]
hey! Is this still an issue? Haven't seen hydration errors in a while now

**Comment by Chades** [comment]
Hi! We didn't tested it afterwards, we just went with shopware storefront and we put pwa on ice, since it was a show blocker. 
We will however try again this summer to make it to work. If there is still a hydration problem, I will reopen this ticket.
