### ISSUE TITLE
[BUG] Language switch behaviour

### ISSUE THREAD

**Issue by elkmod** [vuestorefront/shopware-pwa#1258]
### Describe the bug

Configure a shop with two languages - e.g. `en-GB` and `de-DE` (default). 

* Enter Shop with default language
* Switch language
* Navigate to a different page
* Switch back to default language 

This leads to a cyclic behaviour of navigation reloading and the page remains unusable until you hard-refresh (Ctrl+R).

### Additional context

This behaviour should be fixed and tested with multiple languages and default language settings.

**Comment by patzick** [comment]
as marked in Sprint 48 - this is done, closing
