### ISSUE TITLE
[BUG] installation failing

### ISSUE THREAD

**Issue by JaspervRijbroek** [vuestorefront/shopware-pwa#1261]
### Describe the bug

When running an npx @shopware-pwa/cli init it generates an issue.

To reproduce we have started an empty nodejs 14 docker container.
- docker-compose run --service-ports nodejs bash
- create and cd to the /app directory
- run the command `npx @shopware-pwa/cli init`

A log of the error can be found [here](https://pastebin.com/hFX6GdEj)

We expected this to run without issues and generate the PWA.

**Comment by rrrodzilla** [comment]
Installing yarn got me past this error.

**Comment by patzick** [comment]
hey! Is this still a valid issue?

**Comment by JaspervRijbroek** [comment]
Maybe, i cam check in about 2 weeks (currently on leave)

**Comment by patzick** [comment]
this should no longer be a problem, closing
