### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lbebnowicz** [vuestorefront/shopware-pwa#1271]
### Describe the bug
Storefront has 2 languages: EN and PL. Every click on PL website f.ex open some category add 'en-GB/' to url and redirect to store in EN language. 
There is no language switcher. To go back to PL store. I need to delete 'en-GB/' from url.

![image](https://user-images.githubusercontent.com/30865830/101071360-cc148800-359c-11eb-8f29-29dafd990d2c.png)
![image](https://user-images.githubusercontent.com/30865830/101071415-e0f11b80-359c-11eb-8150-1b4d5af58da3.png)

### Additional context
in shopware-pwa.config.js is entry: defaultLanguageCode: "pl-PL",
shopware version: v6.3.3.1

**Comment by elkmod** [comment]
The entire handling is about to be improved with 0.7.0 release, so these errors will not occur anymore. 

See: https://github.com/vuestorefront/shopware-pwa/pull/1295
