### ISSUE TITLE
[FEATURE] handle displayStateInRegistration settings in useCountry

### ISSUE THREAD

**Issue by mkucmus** [vuestorefront/shopware-pwa#1294]
### Acceptance criteria

- [ ] displayState computed is refactored in order to get the `displayStateInRegistration` once it's available in SW6 configuration

**Comment by niklaswolf** [comment]
Had a conversation with @elkmod about this recently, apparently this field should be deprecated in the API, as it's not used anymore or wasn't used at all.

So this field should be completely removed from shopware-pwa, only `forceStateInRegistration` should be used.

**Comment by jnuricumbo** [comment]
@mkucmus When I call getCountries of UseCountries the fetched countries do not contain the states. I tried to use the defaultsConfigBuilder to get them but it looks that getAvailableCountries of contextService.ts will not take it into account. Is it planned to implement it? planned to show the states in registration form?

Thanks

**Comment by mkucmus** [comment]
hey @jnuricumbo! thanks for reporting the problem 💪🏻 
Of course the default api params should also have covered the countries-related requests and that's what we gonna implement at first.
