### ISSUE TITLE
[BUG] Entering a new address leaks some code during purchase

### ISSUE THREAD

**Issue by Victorw238** [vuestorefront/shopware-pwa#1298]
### Describe the bug
The bug shown in this screenshot is a bug that leaks some code fragments on to the UI during address selection in the checkout process. Such information should be kept hidden because it confuses the end user. 

 Provide reproduction steps
- I'm not sure what caused my bug to appear but I will describe the steps as I experience it.
- First, put any demo product in the cart. Do this while not being logged in.
- Go to checkout
- Choose to register a new account during checkout
- Enter the name, email, password, etc. And then proceed to shipping address
- Since this is a newly registered account going to checkout, the address list will be empty. Please enter a new address.
- After submitting the new address, the checkout page turns into an "error 500" page
- Go back to the home page, and then try the checkout again
- Now, in the shipping address stage, this is what I see: https://prnt.sc/wh5wag
 

### Additional context
 Anything additional which you can add
- device information: Dell PowerEdge T340 Server, running Ubuntu 20.04. Web server is Apache2
- packages version: Shopware 6, and the SwagShopwarePwa is using the master branch

**Comment by niklaswolf** [comment]
I think this is already fixed in #1241.
Which version of shopware-pwa are you using?

**Comment by Victorw238** [comment]
Hello Niklas,
I think I used the most recent one from December 2020

**Comment by niklaswolf** [comment]
Okay, that's strange... maybe I missed something when implementing the fix last year. 
So this needs some looks into it :)

**Comment by patzick** [comment]
This shouldn't be a problem after the checkout refactor. Please let me know if this issue is still valid. Closing for now, thanks for your report!
