### ISSUE TITLE
[BUG] Shipping and payment addresses do not appear in checkout process

### ISSUE THREAD

**Issue by jonaletil** [vuestorefront/shopware-pwa#1299]
### Describe the bug
The addresses for shipment and payment are not being displayed in step 2 (Shipping) and step 3 (Payment)!
Output in console: `Cannot read property 'name' of null`

Tested on PWA demo page (https://shopware-pwa.storefrontcloud.io/)

Furthermore there is also a problem with editing the addresses in account page. 
When trying to change some inputs and saving/updating them nothing happens!
Also I think that the field _House/Apartment number_ is unnecessary

#### Reproduction steps - Checkout
- Add some product item to cart
- Go to checkout
- Switch to steps 2 and 3 (Shipping and Payment)

#### Reproduction steps - My account
- Go to My account
- Switch to My addresses
- Choose some address and click on Edit icon (>)
- Update some inputs and try to update the address

**Comment by niklaswolf** [comment]
Regarding 

> Also I think that the field House/Apartment number is unnecessary

see #1265
