### ISSUE TITLE
[BUG] add-to-cart notification not working anymore

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/shopware-pwa#1304]
### Describe the bug
The add-to-cart isn't working anymore, this can be tested in the demo shop https://shopware-pwa.storefrontcloud.io.
When adding a product to the cart, a notification was and should be shown.

I think the cause is, that the [i18n-plugin](https://github.com/vuestorefront/shopware-pwa/blob/master/packages/nuxt-module/plugins/i18n.js) is not injected properly and thus `undefined` when using it in `logic/notifications/index.js` (  https://github.com/vuestorefront/shopware-pwa/blob/5f2d6a969a64a35eb4f44201ee78ab9690767fd0/packages/default-theme/src/logic/notifications/index.js#L6) which is used in the [notifications-plugin](https://github.com/vuestorefront/shopware-pwa/blob/master/packages/default-theme/src/plugins/notifications.js)

All other plugins use the `inject` function which would make `i18n` available in other plugins, too.
This issue is described here https://medium.com/@valerka/how-to-register-the-plugin-correctly-in-nuxt-js-91ed2d95b81f.

I think it has worked until some time ago only by chance, maybe the loading order has changed or something like that.
I think the `i18n` plugin has to be injected properly to be also available in other plugins :)

**Comment by develth** [comment]
Hmmm, i didn´t even get a `onAddToCart` intercept, like described in docs...

**Comment by develth** [comment]
Yip, the mentioned i18n breaks it. When change it to `rootContext._i18n` it works
