### ISSUE TITLE
[BUG] Images in product gallery are not ordered like in administration

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/shopware-pwa#1306]
### Describe the bug
The pictures on the product detail page are not in the same order as configured in the administration.
The API-Calls (`useCms` and `useProduct`) lack the sorting of the media-association. This should be added to the default api params.
```
associations: {
        media: {
          sort: [
            {field: "position", order: "ASC", naturalSorting: false}
          ]
        }
      },
```

**Comment by niklaswolf** [comment]
I'll provide an PR, you can assign me @mkucmus

**Comment by develth** [comment]
I´m also currently into getting the correct sorting on a product change. may i could support you?

**Comment by niklaswolf** [comment]
@develth support is always welcome :) 
What do you mean by "correct sorting on a product change"?

**Comment by develth** [comment]
@niklaswolf by that i mean that i had a typo :)

**Comment by niklaswolf** [comment]
@develth in this case I'm afraid there is not much to be supported. The solution is described in the issue description and I just need to add it to the default API params. If you want to test it right now, you can add the following to your shopware-pwa.config.js

```
apiDefaults: {
    useCms: {
      associations: {
        media: {
          sort: [
            {field: "position", order: "ASC", naturalSorting: false}
          ]
        }
      }
    },
    useProduct: {
      associations: {
        media: {
          sort: [
            {field: "position", order: "ASC", naturalSorting: false}
          ]
        }
      },
    }
  }
```
You should then see the images beeing ordered correctly :)

**Comment by develth** [comment]
Ok.
I started adding `position` to `useProduct.includes.product_media`and sorted it in the Helper by the Position, because to reduce the load for the API?

**Comment by niklaswolf** [comment]
@develth that's interesting, didn't think about that. Maybe that's indeed the more performant approach. It all depends on where the logic for this should live, in the API or in the frontend. What do you think @mkucmus @elkmod ?

**Comment by develth** [comment]
My Changes would be:

**helpers**:

Add `.sort((a, b) => (a.position > b.position))` between `product.media` and `.map((media) => ...`

**Defaults**
Add `position` to product_media
