### ISSUE TITLE
[BUG] default logo and footer not loaded in Firefox.

### ISSUE THREAD

**Issue by rrrodzilla** [vuestorefront/shopware-pwa#1310]
### Describe the bug

The default theme with a fresh install of shopware-pwa and shopware 6 is not showing the footer or the logo.
The logo, requested at https://www.domain.com/img/logo.svg errors with a 502
The footer, requested at https://shopware6-url.domaincom/store-api/v3/navigation/footer-navigation/footer-navigation errors with a 404

Fresh install of Shopware 6, default options during setup, exposed via SSL over 443.
Fresh install of Shopware-pwa on separate bare server, exposed using nginx following instructions at: https://docs.vuestorefront.io/guide/installation/production-setup.html using letsencrypt ssl over 443

run yarn build && yarn start on pwa server
Navigate to pwa homepage in browser: 84.0.2 (64-bit) Mozilla Firefox for Manjaro Linux
Open browser dev tools, network tab - see output captured in screenshots.

![image](https://user-images.githubusercontent.com/24578097/105768745-71573700-5f22-11eb-8b0d-285d2fb32b88.png)
![image](https://user-images.githubusercontent.com/24578097/105767115-4b309780-5f20-11eb-8c22-84c8f678113d.png)

### Additional context
See linked screenshot.

**Comment by rrrodzilla** [comment]
If I switch to the demo Shopware backend, the footer shows (the logo still does not as it appears to be attempting to retrieve it from my backend.  I presume the footer is showing because there's something I need to create in Shopware itself named footer-navigation?  Is there a tutorial somewhere on how to recreate the demo?

**Comment by niklaswolf** [comment]
For the footer navigation you have to assign a root category for your footer navigation in the configuration of your sales channel in your Shopware Admin.
<img width="1136" alt="Bildschirmfoto 2021-01-26 um 13 01 32" src="https://user-images.githubusercontent.com/16021919/105842560-ade46a80-5fd6-11eb-80d4-c81ed30486dd.png">

**Comment by niklaswolf** [comment]
Logo is served from the app directly, should be located under `static/img/logo.svg`.

**Comment by rrrodzilla** [comment]
Thanks very much niklas.  The good news is, a techie with zero Shopware experience can set up a production instance pretty easily in a couple hours with the documentation provided.  The bad news is I'm struggling to find a cohesive tutorial to get the platform configured in any meaningful way with the Shopware docs.  A meaningful way would be a tutorial that allows me to configure the platform to resemble anything like the demo instance once the demo data is loaded.

I do see the logo.svg in the static directory however its not being served due to a Bad Gateway error.  I'm assuming it's probably an nginx config issue.  I'll hunt it down and resolve. 

I did assign a root category to the footer navigation in the configuration of the shop sales channel, then I executed:
`npx @shopware-pwa/cli init`
followed by `yarn build && yarn start`
and although I can see in the network tab that the footer api call is now succeeding, there is still nothing showing up in the footer section.  I'll work my way through the docs again and look for what I must have missed.

I completely recognize this is not a bug and simply an issue of a new user figuring things out so we can close this issue however I wanted to provide the feedback on the documentation from a newbie's perspective.  Thanks for the assist!

**Comment by rrrodzilla** [comment]
For anybody who faces the same issue regarding images, this was the resolution in the nginx config (slightly different than the documented base vuestorefront nginx config):
```       
        location /img/ {
                proxy_pass http://localhost:3000/img/;
        }
        location /assets/ {
                proxy_pass http://localhost:8000/assets/;
        }
```
The production setup docs for vuestorefront (base product, not the shopware-pwa) uses the following recommended config:
```
location /assets/ {
  proxy_pass http://localhost:3000/assets/;
}
```
Regarding the footer, I tried setting the footer nav to a pre-existing root category which was generated by the demo data and it works so I must have missed something when I tried to create it from my own custom made categories.  I'll have to investigate the docs further.
