### ISSUE TITLE
Happy Birthday!

### ISSUE THREAD

**Issue by elkmod** [vuestorefront/shopware-pwa#1317]
& best wishes from the Shopware team! 💙

**Comment by mkucmus** [comment]
omg, thanks a lot!

**Comment by seilex** [comment]
Happy birthday Maciej - enjoy YOUR day!

**Comment by rmakara** [comment]
@mkucmus 
Do we have a Pull Request for that?

**Comment by mkucmus** [comment]
I'm closing the issue, thanks guys 🍻
