### ISSUE TITLE
Extend Product Data call

### ISSUE THREAD

**Issue by LakeWeb-tech** [vuestorefront/shopware-pwa#1319]
I have the problem that I would like to extend the Product Detail Page with the EAN number and other fields. However, I can't manage to expand the product call to get these fields delivered from Shopware. 
 
 The most important thing for me would be to know how I can explicitly extend the product object to get more data delivered from Shopware

How can I extend or customize calls in vue Storefront?

**Comment by mkucmus** [comment]
Hi @LakeWeb-tech, sorry for a veeery late response 😂 here are the details how extend/modify the request's payload in general:
https://shopware-pwa-docs.vuestorefront.io/landing/cookbook/#_9-overwrite-api-defaults

for product data call I would try with "useCms" as a root property in api defaults. Let us know if it helps :)
