### ISSUE TITLE
Refactor of Top-Navigation

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/shopware-pwa#1324]
The navigation items get only fetched on the client side, which introduces quite a delay and layout shift for rendering the Main Navigation.

Some ideas:
- Fetch data on the server side
- SSR whole main navigation (maybe not a good idea because of desktop vs. mobile)

**Comment by patzick** [comment]
This one is fixed with #1402 and is on stable branch already, navigation is fetched on SSR only if the view contains navigation; closing :)
