### ISSUE TITLE
[BUG] billing address name not transmitted to shopware

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/shopware-pwa#1326]
Right now the name you enter in billing address is not transmitted to Shopware, the name from step 1 "personal information" is used.

There are several options here:
- get rid of name fields in billing address form
- prefill the name fields with the name from personal information
  - allow change of these values, then the new values have to be used when transmitting the order!
  - make the fields readonly in billing address form
- remove the name fields from "personal information", this step would then be only responsible for email-address and password

This issue also is part of the checkout flow improvements and can be handled there.

**Comment by patzick** [comment]
Closing as not relevant since 0.9
