### ISSUE TITLE
[BUG] Polish characters in custom font error.

### ISSUE THREAD

**Issue by Malwurf** [vuestorefront/shopware-pwa#1344]
### Describe the bug
Bug exist when I want to use a custom font on project.
I have a problem with `New Atten` from Typekit but I tested that bug with `Potta One` from Google Fonts.
Font is attached to the project correctly but polish diacritic marks not working correctly.
I built project with `yarn dev` and `yarn build` too and the result is the same.

### Steps
- Choose font e.g. from google fonts which include polish characters ęółśćź
- Attach to project on nuxt.config.js file
- Build project

### Additional context
- font for testing -> [Potta One](https://fonts.google.com/specimen/Potta+One?subset=latin-ext&preview.text_type=custom&preview.text=i%C5%9B%C4%87%20na%20&sidebar.open=true&selection.family=Potta+One)
- font for testing -> [New Atten](https://fonts.adobe.com/fonts/new-atten)
- System - Ubuntu 20.04.2 LTS
- shopware-pwa v. 0.6.1
- storefront-ui v. 0.7.18

### added link to nux.config.js
`    link: [
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Potta+One&display=swap'}
    ]`

**Comment by justyna-13** [comment]
Update from SFUI team: there was a new nuxt project created **without SFUI** and added link in nuxt config to font that was used for tests - Potta One. The result is below
![Screenshot from 2021-02-23 16-58-26](https://user-images.githubusercontent.com/46591755/108968114-a6b98680-7680-11eb-8493-a30a7eaf7d46.png)
Next, Potta One font was changed to another google font Akaya Telivigala (also with Polish characters). And the result is below:
![Screenshot from 2021-02-23 17-19-22](https://user-images.githubusercontent.com/46591755/108968292-e3857d80-7680-11eb-82f5-4b935f799813.png)
Both fonts are displayed properly (with Polish characters) on google fonts website
