### ISSUE TITLE
[BUG] Double opt-in for registration, newsletter and password recovery

### ISSUE THREAD

**Issue by elkmod** [vuestorefront/shopware-pwa#1353]
Shopware offers double opt-in functionalities for user and newsletter-registrations as well as a password reset route which works the same way.

In order to support these flows, the application has to "listen" on the following paths and pass the parameters to the respective API-Endpoints mentioned below AND fetch the corresponding configuration (are double-opt ins enabled?) from the API **during build time**:

**Newsletter Confirmation**

PWA-Route: `/newsletter-subscribe?em=<email-hash>&hash=<subscribe-hash>`

API-Route: `POST /newsletter/confirm` => `hash` and `em` body parameters
| Parameter | Description |
|---|---|
|**hash**|Subscribe Hash|
|**em**|Email Hash|

**Registration Confirmation**

PWA-Route: `/registration/confirm?em=<email-hash>&hash=<register-hash>`

API-Route: `POST /account/register-confirm`
| Parameter | Description |
|---|---|
|**hash**|Subscribe Hash|
|**em**|Email Hash|

**Password Recovery**

PWA-Route: `/account/recover/password?hash=<password-hash>`

API-Route: `POST /account/recovery-password-confirm`
| Parameter | Description |
|---|---|
|**hash**|Subscribe Hash|
|**newPassword**|New Password|
|**newPasswordConfirm**|New Password (equality check)|

**Comment by niklaswolf** [comment]
Regarding passwort-recovery: it should be `pwaHost` + current domain ending here: 
https://github.com/vuestorefront/shopware-pwa/blob/master/packages/shopware-6-client/src/services/customerService.ts#L299 the current default is simply wrong :)
