### ISSUE TITLE
[BUG] Product tabs are over menu dropdown

### ISSUE THREAD

**Issue by super-kamil** [vuestorefront/shopware-pwa#1407]
### Describe the bug

Product tabs are over menu dropdown

![image](https://user-images.githubusercontent.com/708028/112854821-81b89900-90ae-11eb-8607-e7d2ea8c04fa.png)

Version 0.7.2

**Comment by patzick** [comment]
let's see if #1076 will fix that

**Comment by patzick** [comment]
I can't reproduce this issue now, probably it's fixed by now.
