### ISSUE TITLE
[BUG] customer session issue

### ISSUE THREAD

**Issue by lbebnowicz** [vuestorefront/shopware-pwa#1408]
### Describe the bug

customer session issue:

after login on a website and add some product to basket I press ctr + ef5 to refresh website
what happend? I'm logged out automatically, product disappearing from basket but when I add another product, the first one appear immediately

### Additional context
Shopware v6.3.5.1 Stable Version
Shopware PWA 0.7.1

**Comment by mkucmus** [comment]
It was solved - the reason: invalid old cookies.
