### ISSUE TITLE
[BUG] checkout -  cannot proceed to the next step

### ISSUE THREAD

**Issue by lbebnowicz** [vuestorefront/shopware-pwa#1433]
### Describe the bug
In the basket, when selecting the option "I want to create an account", you cannot proceed to the next step
We  have only billing error as you can see on attached screenshot

![image](https://user-images.githubusercontent.com/30865830/115201266-6fea7480-a0f5-11eb-8bfd-2254b3bf102c.png)

### Additional context
Shopware v6.3.5.1 Stable Version
Shopware PWA 0.7.1

**Comment by mkucmus** [comment]
storefrontUrl - because we blocked our testing domain in the backend.

countryId - actual problem

The problem does not take place in the latest stable v0.8.1, tested on:
SW v6.3.5.2 
shopware-pwa: v0.8.1

**Comment by patzick** [comment]
closing as fixed in later versions, let us know if there's still a problem with that in the newest version
