### ISSUE TITLE
[BUG] slow search engine

### ISSUE THREAD

**Issue by lbebnowicz** [vuestorefront/shopware-pwa#1434]
### Describe the bug

Hard to explain in words more than that searching for product takes too long
easier to watch the video 

https://user-images.githubusercontent.com/30865830/115205896-50a21600-a0fa-11eb-8c20-31af391ffd26.mp4

### Additional context
Shopware v6.3.5.1 Stable Version
Shopware PWA 0.7.1

**Comment by develth** [comment]
Seems like Dev-Mode. On my PROD it is ok (~400ms. Not fast, but thats BackendSide 'issue').

**Comment by mkucmus** [comment]
> Seems like Dev-Mode. On my PROD it is ok (~400ms. Not fast, but thats BackendSide 'issue').

yeah, search results page uses asyncData, and in the issue's case most of time takes the TTFB I guess. It's rather an API issue.

**Comment by patzick** [comment]
Agree, closing this one as a backend problem. On demo instance search is okay. I'd suggest upgrade to 0.8.x, maybe this will help a little.
