### ISSUE TITLE
[BUG] Cannot read property 'id' of null in ShippingAddressUserForm

### ISSUE THREAD

**Issue by cruonline** [vuestorefront/shopware-pwa#1446]
### Describe the bug
After guest order with "create account" option, after pressing "continue to shipping" account is created in background.
However after navigating to "Shipping" tab 500 error is displayed  with claiming message "Something went horribly wrong".

Console shows
client.js?06a0:102 TypeError: Cannot read property 'id' of null
    at setup (ShippingAddressUserForm.vue?ebf9:72)

Probably the promise from loadAddresses() is not resolved yet

### Repro
Clear app data (this is important)
Refresh pwa page
Add product to cart
Go to checkout, enter your details, password
Click "continue to shipping"

### Additional context
Shopware 6.3.5.4
phopware-pwa 0.8.1
PWA Integration (v0.2.1)
Edge Chromium 89.0.774.77

**Comment by patzick** [comment]
Thanks for the report!
This was fixed with checkout refactor, closing.
