### ISSUE TITLE
[BUG] Missing dependency in custom theme

### ISSUE THREAD

**Issue by super-kamil** [vuestorefront/shopware-pwa#1451]
### Describe the bug
![image](https://user-images.githubusercontent.com/708028/116260234-cd766500-a776-11eb-8b04-8b233e4875a0.png)

Create new theme:

`npx @shopware-pwa/cli@canary create-theme`
extend from @shopware-pwa/default-theme
run `yarn dev`

NodeJS 15.14.0
shopware-pwa canary (8.2)

**Comment by patzick** [comment]
hey @super-kamil , there are problems with Node v15 now, I'm grouping these issues in #1463 and we plan to resolve that soon.

Could you check this on node v14 and let us know if you still have problems there?

**Comment by super-kamil** [comment]
Hi @patzick, thanks but it does not work.

```
nvm use 14.16.0
npx @shopware-pwa/cli@canary create-theme
yarn dev -> same error

rm -rf node_modules/ yarn.lock my-theme/node_modules/
yarn
cd my-theme && yarn
yarn dev -> same error
```

**Comment by super-kamil** [comment]
thanks @mkucmus. now it works 🎉 this step should be added to the documentation.

**Comment by mkucmus** [comment]
> thanks @mkucmus. now it works  this step should be added to the documentation.

It will be added definitely! thanks for feedback 💪🏻
