### ISSUE TITLE
[BUG] Default language not correclty set

### ISSUE THREAD

**Issue by jnuricumbo** [vuestorefront/shopware-pwa#1453]
### Describe the bug

The default language is not correctly set if this is not english. This is happening in v.0.8.1, tested with a fresh instalation of shopware and shopware-pwa

### Steps to reproduce it

- Remove all domains if any and create only one like this
![image](https://user-images.githubusercontent.com/11697761/116315622-121ef200-a7b1-11eb-804f-5a72e5830d17.png)

-  Update your domains using "yarn shopware-pwa domains"
- Start the shopware-pwa project, maybe clearing the cache is needed
- You will have german language for a second and then the language is set automatically to english, pay attention to the search field in the top bar.
- Setting defaultLanguageCode: 'de-DE' in config does not help.

**Comment by patzick** [comment]
Thanks, @jnuricumbo this should be released with 0.8.2 today or tomorrow :)

**Comment by jnuricumbo** [comment]
@patzick thank you!
