### ISSUE TITLE
[FEATURE] Compatibility with Node 15 and 16

### ISSUE THREAD

**Issue by patzick** [vuestorefront/shopware-pwa#1463]
### Description

Node v16 is released. We're supporting the current LTS v14, but we should check compatibility with the next versions.

### Acceptance criteria

- [ ] Compatibility with Node v16
- [x] Compatibility with Node v15

**Comment by mkucmus** [comment]
the project cannot be upgraded up to node v16 due to old versions of sass-loader in storefront-ui library.

It's recommended to move from node-sass to sass library and start using sass-loader in version ^10 - then the project will be running well.
