### ISSUE TITLE
[BUG] Order object does not return shipping address

### ISSUE THREAD

**Issue by LouisEiermann** [vuestorefront/shopware-pwa#1471]
### Describe the bug
When you place an order while logged in with both a billing and shipping address, you can not display this 
in the order history in the account, because the API does not return the appropriate values. 

@niklaswolf said that you were working on the checkout for Shopware 6.4. It would probably 
be a good idea to test this case together with that new version.

### Reproduction
- Place an order as a logged in user while selecting different addresses for billing and shipping
- Go to your account 
- Access order history of the order you placed earlier
- Only the billing address will be shown

In the vue devtools, the order object in data of the component <SwOrderDetails> does contain
an array with the two addresses but the order object does only list one of the two addresses as the 
specific billing address, there is no listing of the shipping address

### Additional context
Version of Shopware PWA: 0.7.1

![Bildschirmfoto 2021-05-05 um 15 06 02](https://user-images.githubusercontent.com/64272749/117145405-6af31980-adb3-11eb-8be9-3ce3c55753e1.png)

**Comment by patzick** [comment]
closed by #1473
