### ISSUE TITLE
Use-case Shopware 6 PSP plugins

### ISSUE THREAD

**Issue by CrystalG23** [vuestorefront/shopware-pwa#1482]
I want to use these Shopware 6 plugins in my project:

    PayPal https://docs.shopware.com/en/shopware-6-en/extensions/paypal
    Sofort Überweisung ( Klarna ) https://docs.shopware.com/de/shopware-6-de/erweiterungen/klarna
    amazon pay https://docs.shopware.com/de/shopware-6-de/erweiterungen/amazon-pay

I was searching in the documentation for an explanation: How to use the PSP Plugins from Shopware 6 in Shopware PWA.
https://shopware-pwa-docs.vuestorefront.io/landing/concepts/payment.html#process

I would like an Answer, if the compatibility is okay.

**Comment by meeshoogendoorn** [comment]
@CrystalG23 I am not very experienced with building PSP for shopware-pwa but i know paypal has a out of the box integration with Shopware-pwa. I was using a third part PSP from the netherlands and even their plugin worked out of the box.  I would recommend to install them in a sandbox environment and just test if it works. If not u could maybe ask the community on Discord. I think there will be people with experience about this issue.

 https://discord.gg/2sgu5P76
