### ISSUE TITLE
[BUG] locales are not being used 

### ISSUE THREAD

**Issue by BeeJayJayn** [vuestorefront/shopware-pwa#1495]
### Describe the bug
Despite the shop being configured as a german shop in all possible ways the pwa still only utilizes the en-GB.json files from locales

Setup a shop, create a locales in the locales folder of the pwa, try to configure a custom translation and have it be output.

**Comment by patzick** [comment]
hey @BeeJayJayn, please provide reproduction steps. We haven't seen issues with locales.
Please also take a look here: https://shopware-pwa-docs.vuestorefront.io/landing/concepts/snippets.html#translations-snippets

**Comment by BeeJayJayn** [comment]
This is related to the browser languages being english. Probably not something that you should fix, as this is very specific to my setup. Forgot to close.
