### ISSUE TITLE
[FEATURE] Access to plugin configurations (pwa-bundles.json)

### ISSUE THREAD

**Issue by meeshoogendoorn** [vuestorefront/shopware-pwa#1514]
### Description

Now the `pwa-bundles.json` gets generated when running `shopware-pwa plugins`. In the `pwa-bundles.json` some values i have to use in my code are defined. Think of apiKeys and some configuration values for my plugins. Is it a good idea to make this available also to the client in someway that we can blacklist sensitive keys or whitelist only the one we need?

### Example

The Array below exists in `pwa-bundles.json`:

```js
"shippingMethods": [
          "a4139c276ad24bf1ab51cebce3864345"
 ]`
```
This array consist of the id of the shippingMethod named pickup.

On the homepage i have a few dynamic buttons which will display a button to select the shippingMethod pickup. Now i need to hardcode the name of the shippingMethod to filter it out of the `shippingMethods` object of `useCheckout`. 

If i could use the array from `pwa-bundles.json`, it would be dynamic on buildtime .

### Acceptance criteria

- [blacklist sensitive values or whitelist non-sensitive values]
- [Make pwa-bundles.json available to use in code]

**Comment by patzick** [comment]
Hey @meeshoogendoorn 
I've been experimenting with this and I believe recent changes in defaultConfig are coming with help.
I would prefer to avoid exposing the whole pwa-bundle.json file to the frontend, as you pointed out - it might cause problems with important data leaks.

What would you say for the solution below? In `shopware-pwa.config.js`

```js
const defaultsConfigBuilder =
  require("@shopware-pwa/nuxt-module/api-defaults").default
const pluginConfig = require("./.shopware-pwa/pwa-bundles.json")

// your custom things in config
defaultsConfigBuilder().replace("useCms.limit", 15)
defaultsConfigBuilder().add("useCms.includes.product", "extensions")

// here you can add your own key, for example for your composable/plugin
defaultsConfigBuilder().add("myPluginDefaults", pluginConfig['my-plugin-name'].configuration.yourKey)

module.exports = {
 ...
}
```

This way you have control over what's exposed to the frontend on build time.
-
