### ISSUE TITLE
[BUG][UseProductConfigurator] Product variations not working after update 0.9.0

### ISSUE THREAD

**Issue by meeshoogendoorn** [vuestorefront/shopware-pwa#1544]
### Describe the bug
When selecting a product variant an alert will show with the following content.
`There is no available product for selected options`

This behaviour is not correct because the variants i'm selecting exist.

### REPRODUCTION

Go to the following url of your demo instance.
https://shopware-pwa.storefrontcloud.io/93-Crop-Jeans/290980000.3

Select a color variant and the alert will show up with the text above.

**Comment by mkucmus** [comment]
thanks @meeshoogendoorn ;) you have found an 🦄
I hope it's a last place where we access the data in old way 👍🏻
