### ISSUE TITLE
[BUG] Productlist seconds api call will clear filter values

### ISSUE THREAD

**Issue by SimonMarx** [vuestorefront/shopware-pwa#1552]
### Describe the bug

When you change filters on the Productlist there are 2 calls triggered to the /product-list/{id} api of shopware.

An example of the body for the first request:

`{"limit":10,"includes":{"product":["name","ratingAverage","calculatedPrice","calculatedPrices","calculatedListingPrice","cover","id","translated","options","seoUrls"],"product_media":["media"],"media":["thumbnails","width","height","url"],"calculated_price":["unitPrice","quantity","listPrice"],"product_group_option":["name","id","group","translated"],"product_group":["id","name","options","translated"],"property_group":["id","translated","options"],"property_group_option":["name","translated","id","colorHexCode","media","group"]},"manufacturer":["04d9c87f9af048f0b21e119992a8380a"],"properties":[]}`

This body includes all selected filter values e.g. `manufacturer` and `properties`, which is important when you have aggregations which returns different values depends of the user selected filters.

The second request to the same endpoint only contains: `{"includes":{"product_listing":["aggregations"]}}`, which will return all possible aggregations as you have them when the user does not selected any filter.
Since the filter in the types component will be overwritten with the response body of the second api call, the aggregations might not be correct because the seconds request does not includes the users selected filters.

### Steps to reproduce

**Create an EventListener in Shopware to extends the ProductListingCriteriaEvent**
An example part of my code:

```php
public static function getSubscribedEvents()
    {
        return [
            ProductListingCriteriaEvent::class => ['handleListingRequest', -10],
            ProductListingResultEvent::class => ['handleResult', -10],
        ];
    }

    public function handleListingRequest(ProductListingCriteriaEvent $event): void
    {
        $criteria = $event->getCriteria();
        $request = $event->getRequest();

        $this->handleCustomAggregation($request, $criteria);
    }

    public function handleResult(ProductListingResultEvent $event)
    {
        $result = $event->getResult();
        $request = $event->getRequest();

        $result->addCurrentFilter(self::FILTER_MODEL, $this->getSelectedModel($request));
    }

private function handleCustomAggregation(Request $request, Criteria $criteria): void
    {
        // get the selected manufacturer from the request (filter)
        $manufacturer = $this->getSelectedManufacturer($request);
        // get the selected model from the request (filter)
        $model = $this->getSelectedModel($request);

        $criteria
            ->addAssociation(CustomProductExtension::FIELD_MODELS)
            ->addAssociation(\sprintf('%s.manufacturer', CustomProductExtension::FIELD_MODELS));

        // depending of the manufacturer selection, the EntityAggregation will be filtered to the matching models
        $criteria->addAggregation(
            new FilterAggregation(
                'model-filter',
                new EntityAggregation(
                    'model',
                    \sprintf('product.%s.id', CustomProductExtension::FIELD_MODELS),
                    ModelDefinition::TABLE_NAME
                ),
                [
                    new EqualsFilter(
                        \sprintf('product.%s.manufacturer.id', CustomProductExtension::FIELD_MODELS),
                        $manufacturer
                    )
                ]
            )
        );

        if (null === $model) {
            return;
        }
        // implement post Filter when model was selected
    }
```

**Create a new listing type in  src/components/listing/types/model.vue**

```vue
<template>
  <div>
    <div class="sf-heading filters__title" style="text-align: left !important;">
      {{ $t(filter.label) }}
    </div>
    <!-- Options will be empty after seconds product-listing request -->
    <pre>{{options}}</pre>
  </div>
</template>


<script>
export default {
  components: {},
  props: {
    filter: {
      type: Object,
      default: () => ({}),
    },
    selectedValues: {
      type: Array | Object,
      default: () => ([]),
    },
    currentFilters: {
      type: Object,
      default: () => ({}),
    },
  },

  computed: {
    options() {
      return this.filter.entities || this.filter.options || [];
    }
  },

  watch: {
    selectedModel(val) {
      this.$emit('toggle-filter-value', {
        ...this.filter,
        type: 'max',
        value: (!val) ? val : val.name,
      })
    }
  },
}
</script>

<style scoped lang="scss">
.sf-heading {
  --heading-text-align: left;
}
</style>
```

The options of your filter are always empty, since you have build an aggregation which has dependencies e.g. to the manufacturer selection, which is not present in the second api call.

### Additional context
Versions:
- @shopware-pwa/nuxt-module: 0.9.0
- @storefront-ui/vue: 0.10.5

**Comment by patzick** [comment]
Thanks for your report!

probably related to #1530, leaving it here for the context

**Comment by mkucmus** [comment]
Hi @SimonMarx, I think I studied your case enough to propose something :)

As it's described, you are adding some custom aggregation when the "manufacturer" filter is applied.
As you noticed, we assign the "aggregations" object from the second call to the current listing configuration, that's why your custom aggregation isn't there, because the whole aggregation property is overwritten. 
```
const result = await searchMethod(searchCriteria);
      // TODO: investigate why filters are not complete
      const allFiltersResult = await searchMethod({
        query: searchCriteria.query,
        includes: { product_listing: ["aggregations"] },
      });
      _storeAppliedListing.value = Object.assign({}, result, {
        aggregations: allFiltersResult?.aggregations, // HERE we are
      });
```

what we can do here is to provide a merge policy on the whole "aggregations" object, to keep the properties from the first call - to be like
```
      
      const firstResponse = {
        aggregations: {
          manufacturer: {

          },
          "custom-aggregation": {

          }
        }
      }

      const secondResponse = {
        aggregations: {
          manufacturer: {

          },
          productNumber: {

          }
        }
      }

      result = firstResponse + secondResponse

      cosnt result = {
        aggregations: {
          manufacturer: {

          },
          "custom-aggregation" : {

          },
          productNumber: {

          }
        }
      }
      ```

thanks to this we won't loose all the aggregations we got from second call, and we keep the aggregation taken from the first one. And we still do nothing with activeFilters (they come from the first call only and it's OK). 

```
aggregations: allFiltersResult?.aggregations, // that will be changed, no replacing -> merging
```

cc: @patzick
