### ISSUE TITLE
[FEATURE] Support for Shopware landing pages

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/shopware-pwa#1586]
### Description

As @elkmod added support for landing pages (https://github.com/elkmod/SwagShopwarePwa/releases/tag/v0.3.1), it'd be really cool to be able to use this feature in shopware-pwa.
I think the only thing that has to be done is to duplicate `components/views/frontend.navigation.page.vue` to `components/views/frontend.landing.page.vue` (at least that's what my tests say.)

### Acceptance criteria

- [ ] PWA is able to resolve routes that are landing pages and render the CMS-Page.

**Comment by patzick** [comment]
Great job figuring that out! Thank you :)

**Comment by niklaswolf** [comment]
Was not that hard as you can see 😂
But thanks 😊
