### ISSUE TITLE
[FEATURE] Customfields when creating an order

### ISSUE THREAD

**Issue by meeshoogendoorn** [vuestorefront/shopware-pwa#1594]
### Description

It would be great to see the possibility to save customFields to an order when doing a post request to the 

`/store-api/checkout/order` endpoint.

This way it is possible to save a delivery date to the order on the initial createOrder request. I have seen some plugins in the store using customFields for saving some data to an order.

### Acceptance criteria

- [ set customFields on initial createOrder request to endpoint `/store-api/checkout/order`]

**Comment by mkucmus** [comment]
hey @meeshoogendoorn! 
According to the [store-api documentation](https://pwa-demo-api.shopware.com/trunk/store-api/_info/swagger.html#/Order/createOrder), the only allowed fields are "customerComment", "affiliateCode" and "campaignCode".
![image](https://user-images.githubusercontent.com/5596960/144409693-e38e9d94-5ae0-4c18-81fb-8f50b30ce28f.png)


>I have seen some plugins in the store using customFields for saving some data to an order.
You mean the plugins may listen to requests and if there is some specific field attached withing createOrder request - then it's being used for further actions.

We could open the API for createOrder request's params if using extra info in the payload is a common case 🤔
