### ISSUE TITLE
[BUG] Breadcrumbs not displayed on detail page on initial load

### ISSUE THREAD

**Issue by niklaswolf** [vuestorefront/shopware-pwa#1596]
### Project type
- [x] Project (generated by CLI)
- [ ] Contribution (cloned/forked from GH)

### Describe the bug
When hard reloading a detail page the breadcrumbs aren't displayed despite them being available in the page-oject from the CMS. I have the guess that this is maybe a reactivity issue in the `useSharedState` composable, but I'm not quite sure.
I'm not always able to reproduce this on your demo instance, this also can be a race condition.

EDIT: Seems like the SSR of the breadcrumbs doesn't work, the breadcrumbs are also empty in the HTML. I added the following logging to `layouts/default.vue`
```
const getBreadcrumbs = computed(() => {
      console.log("BREADCRUMBS", breadcrumbs, breadcrumbs.value)
      return breadcrumbs.value.map((breadcrumb) => {
        return {
          // map to SFUI type
          text: breadcrumb.name,
          link: root.$routing.getUrl(breadcrumb.path),
        }
      })
    })
```
This results in the following log on the server:
```
BREADCRUMBS RefImpl {                                                                                                                                                                                   10:02:35
  value: [Getter/Setter]
} []

```
On the clientside I get the same log, so the breadcrumbs array is empty. 

### Additional context
- node version:
- shopware-pwa version: 0.9.1
- Shopware 6 detailed version: 6.4.1.x
- system:

**Comment by patzick** [comment]
I cannot reproduce this issue for the current canary. 
@niklas-wolf can you confirm it's fixed?

**Comment by niklaswolf** [comment]
@patzick  I'm sorry, I have to pass on this one, as we currently haven't upgraded any of our projects yet to RC-1 and we only work with fixed versions, not canary and I currently don't have the time to setup a clean new project...
But if you can't reproduce, I trust you that it's fixed ;) :)
