### ISSUE TITLE
[BUG] Product extensions are not included in API response

### ISSUE THREAD

**Issue by patzick** [vuestorefront/shopware-pwa#1608]
### Describe the bug

related: #1593 

We need to check the category and product page for `useCms`. Including `extensions` is not working and the API response is not containing these fields.

![image](https://user-images.githubusercontent.com/13100280/127179353-858cdf28-898d-448e-b294-c5abc5fa724d.png)

### Acceptance criteria
- [ ] track the problem by adding `extensions` into apiDefaults config 
- [ ] extensions should be returned in category listing and product page

**Comment by BeeJayJayn** [comment]
@mkucmus any updates on this? I'm currently having to consider feature for the release and if this is not available I will have to move it out of the MVP.

**Comment by mkucmus** [comment]
> @mkucmus any updates on this? I'm currently having to consider feature for the release and if this is not available I will have to move it out of the MVP.

yes, I put my findings in related issue: https://github.com/vuestorefront/shopware-pwa/issues/1593#issuecomment-888260862

**Comment by BeeJayJayn** [comment]
Missed that one, thanks!

Does that mean, we wont see a fix in 0.10.0?

**Comment by patzick** [comment]
so this will be resolved by #1593 which is connected directly to shopware API
