### ISSUE TITLE
[BUG] Getting error when passing root to useUser

### ISSUE THREAD

**Issue by stigvanbrabant** [vuestorefront/shopware-pwa#1640]
### Project type
- [x] Project (generated by CLI)
- [ ] Contribution (cloned/forked from GH)

### Describe the bug

I'm getting a type error when following an example from the documentation about the 'ApplicationVueContext', where should i be getting the 'ApplicationVueContext' from? Also i'm getting a deprecation warning about using the root from the setupContext.

### Additional context
- node version: v12.22.5
- shopware-pwa version: 0.9.1
- system: macOS Big Sur 11.4

![image](https://user-images.githubusercontent.com/14889538/130586984-73189fff-bbcd-49a8-a0c9-564a77ba353e.png)

**Comment by meeshoogendoorn** [comment]
I had the same issue when testing with version 1.10.1 but there it is correct because root is removed. I removed the lang="ts" parameter from the script tag because i wasn't using any typescript in that component. if you aren't using typescript that is a solution.

**Comment by patzick** [comment]
hey @stigvanbrabant!
As the root itself is deprecated and will not be passed in `setup` method in future we also removed it from the composables. Soon I'll write an explanation in docs about how the context is passed, but in general - you will not have to pass any context, in useUser case it will be just `const {user, ...} = useUser()`

closing it now as resolved
