### ISSUE TITLE
[Bug] Build uses default domains first

### ISSUE THREAD

**Issue by Jung-GT-Icons** [vuestorefront/shopware-pwa#1671]
### What happened?

When you build the shopware-pwa it uses the default domains https://pwa-demo-api.shopware.com from https://github.com/vuestorefront/shopware-pwa/blob/v0.8.3/compatibility.json.
The used pwa versions are
```
"@shopware-pwa/commons": "^0.8.3",
"@shopware-pwa/nuxt-module": "^0.8.3"
```
and the shopware-pwa.config.js is in the root folder where the build is done.

Thx for your help!

### Steps To Reproduce

1. Create a new entry in the hosts file
`127.0.0.1   pwa-demo-api.shopware.com`
2. Create a folder and switch into it
`mkdir pwa_test && cd pwa_test`
3. Create a simple **shopware-pwa.config.js**
```
module.exports = {
  shopwareEndpoint: 'https://some.dummy.com',
  shopwareAccessToken: 'SomeToken',
  pwaHost: 'https://some.dummy.com',
  defaultLanguageCode: 'de-DE'
}
```
4. Build the pwa application
`npx @shopware-pwa/cli@^0.8.3 init --ci --username doesNotMatter --password notRelevant`

Then you should see a message similar to the log output. This implies the demo domain is used and it tried to connect there.
It should have tried to connect to some.dummy.com not to pwa-demo-api.shopware.com, right?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Previous versions (write which one)

### Environment

```markdown
- OS: Windows and Linux
- Node: 14.16.1
- Shopware API: not relevant
- Shopware PWA version: 0.8.3
```

### Relevant log output

```shell
npx @shopware-pwa/cli@^0.8.3 init --ci --username doesNotMatter --password notRelevant
√ Preparing Nuxt project
√ Updating configuration for option: ^1.0.0-RC.1
√ Generating project files
UNEXPECTED ERROR Error: connect ECONNREFUSED 127.0.0.1:443
Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443,
  config: {
    url: 'https://pwa-demo-api.shopware.com/prev/api/oauth/token',
    method: 'post',
    data: '{"client_id":"administration","grant_type":"password","scopes":"write","username":"doesNotMatter","password":"notRelevant"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 123
    },
```

**Comment by patzick** [comment]
related #1507 backported #1510 for v0.8.4
