### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by senna765** [vuestorefront/shopware-pwa#1672]
### What happened?

![image](https://user-images.githubusercontent.com/26200870/133889526-1f2b400f-613c-4992-ad01-0351e16c8c83.png)
I can't install pwa instance, whatever url I provide, it gives me error `url is not defined`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Which element is affected?

CLI

### Environment

```markdown
- OS: Ubuntu 20 LTS
- Node: 16.9.1
- Shopware API: LTS
- Shopware PWA version: LTS
```

**Comment by patzick** [comment]
Hey @senna765 
Would you please try running it on Node14? We haven't tested it yet for Node16.

Let me know if that helps.

**Comment by patzick** [comment]
closing for now, we'll take care of Node v16 compatibility in future
