### ISSUE TITLE
price handling on category and product page by login logout  with different tax

### ISSUE THREAD

**Issue by brontius** [vuestorefront/shopware-pwa#1673]
### What happened?

On category page and product detail page the prices not reactiv if you login or logout to account with different tax.
You are on a catagory page and not logged in. The prices are shown with tax. When you log in to a business account with net prices the prices still displayed with tax. After you reload the page or click on next page the prices will display correctly.
The same way if you log out from account without tax. The prices are still displayed without tax until you reload the page or click to another page.
 

### Steps To Reproduce

.env:
HOST=0.0.0.0
PORT=3000
ADMIN_USER=admin
ADMIN_PASSWORD=
ENABLE_DEVTOOLS=true
NODE_ENV=dev
EXPERIMENTAL_IMAGE_PROCESSING_SERVER=

Initial installation
npx @shopware-pwa/cli@canary init

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Canary (generated by CLI)

### Environment

```markdown
macosx High Sierra 10.13.6
node v14.17.5
1.0.0-canary.1492 also in 1.0.0-canary.1478
Nuxt @ v2.15.8
shopware v6.4.3.1 Stable Version
PWA integration 0.3.1
```

**Comment by patzick** [comment]
hey, @brontius thanks for filling this issue.
The reason for that is we don't refresh the whole page after the user is logged in / logged out. That's why only when you refresh/change the page after these actions you have desired results.
Your case is perfectly valid, I don't think it matches most of the use cases though.

What would you say to register interceptor methods from `useUser` and refresh the page on these events?

```js
setup() {
  const { onUserLogin, onLogout } = useUser()

   function refreshPage() {
    // logic to refresh page - you need to choose the method that suits you, 
    // for example refreshing the entire page and invoke SSR or just force Vue router reload.
  }

  onMounted(() => {
    onUserLogin(refreshPage);
    onLogout(refreshPage);
  })
}
```

let me know if that solution works for you

**Comment by brontius** [comment]
thank you for your answer, seen from this site it is not a bug - sorry .
To your suggestion. I have insert the interceptor on the page and it works for us if we do a Vue router reload! Easy way.
The harder way is to make a refresh since I have to ensure that the right page data are fetched before. But at the moment for the most is it ok.

**Comment by patzick** [comment]
Perfect!
Thanks for reaching out to us, glad we could sort that out :)
