### ISSUE TITLE
[FEATURE] Add new slots for SwProductCard and SwProductListing

### ISSUE THREAD

**Issue by benjamin-ott** [vuestorefront/shopware-pwa#1694]
### Description

A new slot should be added for the components SwProductCard and SwProductListing in order to make them injectable.
E.g. the ProductCard is used across multiple other components and this way the content of the ProductCard could be replaced in one place.

SwProductCard
`<SwPluginSlot name="product-card-wrapper" :slot-context="product">`

SwProductListing
`<SwPluginSlot name="product-listing-wrapper" :slot-context="getElements">`

### Acceptance criteria

- [ ] new slot in card
- [ ] new slot in listing

**Comment by patzick** [comment]
Slot names and context can be found in #1700 

Plugin can inject into slot before, after or replace slot context. Example for injecting after the slot:
```
<template>
  <div>
    <slot />
    <h3> my additional content after the slot content </h3>
  </div>
</template>
```
