### ISSUE TITLE
[FEATURE] Needed slots in checkout components

### ISSUE THREAD

**Issue by elkmod** [vuestorefront/shopware-pwa#1698]
There have been requests to add additional, generally available slots in our checkout components

![slots](https://user-images.githubusercontent.com/7780750/135609777-c5bc3b00-3e24-4311-b7d8-3cfa85839096.png)

**Comment by patzick** [comment]
Slot names and context can be found in #1700 

Plugin can inject into slot before, after or replace slot context. Example for injecting after the slot:
```
<template>
  <div>
    <slot />
    <h3> my additional content after the slot content </h3>
  </div>
</template>
```
