### ISSUE TITLE
[Bug] Empty wishlist page

### ISSUE THREAD

**Issue by plewsza** [vuestorefront/shopware-pwa#1704]
### What happened?

If you try to add product to the wishlist, the notifications will work fine, but there will be no any product on the wishlist page.

![wishlist](https://user-images.githubusercontent.com/6109149/136928324-b002e176-5993-497f-8bbf-61f281dce12d.png)

### Steps To Reproduce

1. Add product to the wishlist
2. Go to the wishlist page

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Environment

```markdown
- OS: 
- Node: 
- Shopware API: 6.4.2.1 (stable version)
- Shopware PWA version: 0.9.2
```

**Comment by patzick** [comment]
Thanks, @plewsza!
I can reproduce that on the latest stable release. On the canary version, it's already fixed, though: https://shopware-pwa-canary.storefrontcloud.io/
It will be shipped with 1.0.0-RC.3
