### ISSUE TITLE
[Bug] Change of product variant cause change domain url

### ISSUE THREAD

**Issue by lbebnowicz** [vuestorefront/shopware-pwa#1717]
### What happened?

change of product variant cause change domain url

### Steps To Reproduce

You need to have at lease two languages (two domains) on your sales channel.
Switch to the domain which is not a standard domain f.ex: `localhost/en-GB` 
Go to product detail page of product which have variants available
Change variant
Your domain will change to the standard
If you have also different currency, currency as is connected to domain will switch as well...

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Canary (generated by CLI)

### Environment

```markdown
- OS: Ubuntu latest
- Node: v10.24.1
- Shopware API: checked on v6.4.2.1 Stable Version and v6.3.5.1 Stable Versio
- Shopware PWA version: checked on 0.9.2 and 0.7.1
```

**Comment by patzick** [comment]
Hey @lbebnowicz !
Have you tried it with the newest RC version?
As the related bug in the current API version (#1712) is resolved we'll update the demo API version to check if this problem still occurs. I'll give you an update in the next few days if we can reproduce that after the API update.

**Comment by patzick** [comment]
hey @lbebnowicz 
we could reproduce this issue and the fix is already in PR. You can easily implement this solution in your code from `SwProductDetails.vue` you can take it from here: https://github.com/vuestorefront/shopware-pwa/pull/1720/files#diff-ec45eb840821305b5711fc847eb3e95258f4a928dc7951b671adb382d6438d80L120

Let me know if that helps you, cheers :)

**Comment by lbebnowicz** [comment]
Hi Patryk,

works perfectly :)

Thank you for your help and effort!

wt., 2 lis 2021 o 09:01 Patryk Tomczyk ***@***.***>
napisał(a):
