### ISSUE TITLE
[Bug] Product Images in Safari are not showing

### ISSUE THREAD

**Issue by benjamin-ott** [vuestorefront/shopware-pwa#1718]
### What happened?

Hi!
it seems there is a problem with images in Safari. Especially in the product boxes.

### Steps To Reproduce

1. Go to https://shopware-pwa-canary.storefrontcloud.io in the Safari Browser.
2. Look at the Product Slider at the bottom. In the Product boxes are no image

![Bildschirmfoto 2021-10-29 um 13 55 15](https://user-images.githubusercontent.com/8365682/139430051-f82bc0b4-69cb-4475-8313-711817870f2b.png)
s.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Canary (generated by CLI)

### Which element is affected?

default-theme

### Environment

```markdown
- OS: 
- Node: 
- Shopware API: 
- Shopware PWA version:
```

**Comment by kasztof** [comment]
I also observe this issue on our test instance. I noticed that when you click on the address bar and add `/` to the URL, the images suddenly appear. Perhaps some event is being fired that updates the images?

**Comment by ewaldmedia** [comment]
I can also confirm the error on iPhone with different browsers. But I delete the `/` and don't add it and the images appear.

**Comment by mkucmus** [comment]
the issue has been solved in UI library which is updated to get rid of the problem.
