### ISSUE TITLE
Docs site is down

### ISSUE THREAD

**Issue by Crisis2010** [vuestorefront/shopware-pwa#1719]
### What happened?

Looks like Docs site hosting go down https://shopware-pwa-docs.vuestorefront.io/

![image](https://user-images.githubusercontent.com/24792724/139480317-62b364ec-35ca-4cdb-b3a0-34caabdb577b.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

**Comment by mkucmus** [comment]
thanks for reporting. we got rid of the problem and now it's working well back again!
