### ISSUE TITLE
[Bug] nuxt-child not working in my account pages

### ISSUE THREAD

**Issue by meeshoogendoorn** [vuestorefront/shopware-pwa#1727]
### What happened?

When trying to load the addresses or orders in my account they are not displaying.

<img width="1633" alt="Screenshot 2021-11-08 at 10 33 39" src="https://user-images.githubusercontent.com/55089200/140717865-ee8e084a-caee-472d-a93d-68357d0cce04.png">
The white box should load the child component.

I don't see any issues in Chrome Developer Tools.

parent components files affected:
- `src/pages/account/orders.vue`
- `src/pages/account/addresses.vue`

child components files affected:
- `src/pages/account/orders/index.vue`
- `src/pages/account/addresses/index.vue`

WHen copying the content of the childs template tag to the parent it is loading my addresses and orders and it always worked but since last update it stopped working. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Which element is affected?

default-theme

### Environment

```markdown
- OS: macos Big Sur
- Node: 14
- Shopware API: 6.4.4.1
- Shopware PWA version: 1.0.0-RC.3
```

**Comment by patzick** [comment]
hey @meeshoogendoorn 
I just tried to reproduce this issue on current version and cannot see the result you mentioned.
1. I created the page `src/pages/account/orders.vue` and displayed the effect
2. I deleted this file and created a new one in `src/pages/account/orders/index.vue`

in both cases I have correct result as a custom page
![image](https://user-images.githubusercontent.com/13100280/140761414-461feb3d-4d0b-4c3f-b69a-b202f4831ab6.png)

can you provide the steps to reproduce your case? Maybe just `yarn` and `yarn dev` once again would help?

**Comment by meeshoogendoorn** [comment]
@patzick I fixed this by removing the nuxt-child and replacing it with the actual content. I think personally it have something to do with the issue we spoke about in the discord. Where refs stay empty but the api calls will be done.
https://discord.com/channels/770285988244750366/786224408460656701/907961027998670879

Did u already have a chance to look at this?

**Comment by patzick** [comment]
@meeshoogendoorn I can reproduce the issue with products listing and I'm investigating that, will let you know as soon as I'll have solution for that
