### ISSUE TITLE
[Bug] composables problems without ssr

### ISSUE THREAD

**Issue by super-kamil** [vuestorefront/shopware-pwa#1730]
### What happened?

In `layouts/default.vue` create this minimal setup: 

```html
<template>
  <section class="layout">
    <nuxt-link :to="$routing.getUrl('/')">home</nuxt-link>
    <nuxt-link :to="$routing.getUrl('/some-category')">category</nuxt-link>

    {{ getBreadcrumbs }}
  </section>
</template>
<script>

import ...

export default {
  setup() {
    const { breadcrumbs } = useBreadcrumbs();
    const getBreadcrumbs = computed(() => {
      return (
        breadcrumbs.value?.map((breadcrumb) => {
          return {
            text: breadcrumb.name
          }
        }) || []
      )
    });

    return {
      getBreadcrumbs
    }
  },
  ...
}
</script>
```

Click on the links. 
Behavior with **enabled SSR**: breadcrumbs are **changing**.
Behavior with **disabled SSR**: breadcrumbs are **not changing**.

The same happens with other composables like `useCms`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Canary (generated by CLI)

### Which element is affected?

composables

### Environment

```markdown
- OS: Win 11
- Node: 15.14.0
- Shopware API: v6.4.6.0
- Shopware PWA version: 1.0.1
```

**Comment by mkucmus** [comment]
Hi @super-kamil! Please upgrade you project to the v1.0.1 or @canary. #1728 fixes the issue.
