### ISSUE TITLE
[DOCS] Explain aliased imports like '@' and '@theme'

### ISSUE THREAD

**Issue by K3vinF** [vuestorefront/shopware-pwa#1734]
### It is not clear from the documentation what '@' and '@theme' mean.

When overriding / copying a component from the base theme it is confusing what import like this actually do

```import SwTopNavigation from "@/components/SwTopNavigation.vue";```
```import SwTopNavigation from "@theme/components/SwTopNavigation.vue";```
```@import "@theme/assets/scss/variables";```

I found some of the code that makes these imports happen, but it would be nice to have some proper documentation for this.

https://github.com/vuestorefront/shopware-pwa/blob/master/packages/nuxt-module/src/module.ts#L84

### Acceptance criteria
- [ ] Explain the different available options for importing componentsn / oode;
- [ ] Update the Cookbook: https://shopware-pwa-docs.vuestorefront.io/landing/cookbook/

**Comment by mkucmus** [comment]
Hello! we are still working on the documentation, thanks for pointing an unclear area of that.

Basically, it can be described as:
**@theme** - alias that points the directory, where the theme is configured in `shopware-pwa.config.js` file under `theme` property. so by default it's `@shopware-pwa/default-theme`, and it's inside your node_modules, unless the value for `theme` option i provided.

**@**  - alias always points the files in your local project files (where nuxt.config.js and shopware-pwa.config.js files are located) `%project_dir%/src/`

Basically that's it. Now, see a working example.

1. Let's override some component from `@shopware-pwa/default-theme`, to do so, run `shopware-pwa override` command and pick up the SwLogin component from the list.
```
✔ Type or select component to override · /SwLogin.vue
[CLI > override] Component overrided. You can edit it in src/components/SwLogin.vue
```
2. do some customization in the recently created file.
3. create some page, like `src/pages/test.vue` which may look like:
```
<template>
    <div>
        <ProjectSwLogin /> this will display a customized local one
        <DefaultThemeSwLogin /> this will display a default one
    </div>
</template>
<script>
import ProjectSwLogin from "@/components/SwLogin.vue";
import DefaultThemeSwLogin from "@theme/components/SwLogin.vue";

export default {
    components: {
        ProjectSwLogin, // your local component, created within override CLI command - customized
        DefaultThemeSwLogin // base component, still in @shopware-pwa/default-theme - untouched
    },
    setup() {
        return {

        }
    }
}
</script>
```

Thanks to the aliases, you can mix imports and use both, from theme you inherit and the local project you are currently working on.

**Comment by K3vinF** [comment]
Thanks for the clarification!
If I can find the time, I will try to use the provided explanation and make a merge request to update the docs!
