### ISSUE TITLE
[FEATURE] Support for Meta Descriptions and Title

### ISSUE THREAD

**Issue by PaulSchumacher** [vuestorefront/shopware-pwa#1739]
### Description

The SEO data from the categories should be used in the PWA.

### Acceptance criteria

- [ ] Meta Description should be set depending on the category
- [ ] Title should be set depending on the SEO-Title of the category

**Comment by mkucmus** [comment]
Hi @PaulSchumacher, currently we are facused on other parts of the application. 
To achieve support for meta descriptions and title, you would have to:
1. override the `_.vue` page (inherited from https://github.com/vuestorefront/shopware-pwa/blob/master/packages/theme-base/dist/pages/_.vue) - copy it into your theme, in `pages/` subdir.
2. add config into the page's definition like `head() {}` section that returns title and other stuff you want to bind dynamically
```js
  head() {
      return {
        title: this.metaTitle,  
      }
    },
```
3. in the `setup` function, export computed property that depends on the `page` from `useCms`
```js
...
return {
      metaTitle: computed(() => staticPage.value?.category?.translated?.metaTitle ||  staticPage.value?.category?.translated.name),
...
```

example above uses `category` as a source of metaTitle, but it can be also a `product` object if it's a `product` PDP response.

**Comment by meeshoogendoorn** [comment]
@mkucmus am i correct that there is no support for landing pages yet?
