### ISSUE TITLE
[FEATURE] Add possibility to disable or adapt default session refreshing in nuxt api-client plugin 

### ISSUE THREAD

**Issue by stigvanbrabant** [vuestorefront/shopware-pwa#1740]
### Description

For a project i am working on there have been quite a few adaptions to the user object and to the way authentication works and various other use cases. Because of this i don't use most composables provided by ` @shopware-pwa/composables` package. All is working but i've noticed some calls are being done that i cannot control, these are coming from `/.nuxt/api-client.js` which is created by the ` @shopware-pwa/nuxt-module` package. Would it be possible to add custom functionality here instead of the default? or maybe a possibility to disable it so i can handle it myself?

![image](https://user-images.githubusercontent.com/14889538/143891413-92883821-5843-4d59-8615-6a07d9f6fdb8.png)

### Acceptance criteria

- [ ] Add possibility to disable or adapt default session refreshing in nuxt api-client plugin

**Comment by mkucmus** [comment]
Hi @stigvanbrabant! 
You can overwrite the whole logic inside api-client plugin. To do so, create a new file (or copy existing - much safer :) ) at `src/plugins/api-client.js` inside your project and do whatever you want inside 👍🏻

**Comment by stigvanbrabant** [comment]
Hi @mkucmus! Thanks for the response! Ah i thought i tried doing that already, but i will try it out again! I will post an update here once i have done that.

**Comment by stigvanbrabant** [comment]
@mkucmus I seem to be able to overwrite the api-client file, but there are some variables that are included during build i think? How do i get this variables dynamically or is this not necessary? (mainly the apiDefaults as i think i can just fetch the others from my environment variables?)

https://github.com/vuestorefront/shopware-pwa/blob/62926014afbc10ec9965e945e7b83c5979141789/packages/nuxt-module/plugins/api-client.js#L19-L44

**Comment by mkucmus** [comment]
mhm, you're right. You can freely get simple values from env I guess. 
the apiDefaults you can get from a nuxt's context object which is available in the plugin. the path would be: `context.$shopware.state.shopwareDefaults` and that state is based on config set in `shopware-pwa.config.js`.

**Comment by mkucmus** [comment]
> I'm unable to fetch the defaults from the context, as i think this plugin is what injects that in nuxt's context.

ok, so importing the defaults from `shopware-pwa.config.js` in api-client would be an option. If it works for you I would close the issue, because it's more about the possibility of overwriting api-client logic.

**Comment by stigvanbrabant** [comment]
@mkucmus i just added the api defaults object static in my project and imported it from there, i guess it works but now on server side calls it sometimes still uses the apiDefaults from the '@shopware-pwa/composables'. But maybe this is an unrelated other issue?
