### ISSUE TITLE
[Bug][Plugins] All plugins get initialized twice

### ISSUE THREAD

**Issue by meeshoogendoorn** [vuestorefront/shopware-pwa#1744]
### What happened?

When creating a new custom plugin it will be initialized twice and it will register all interceptors twice that are defined in the plugin.

See the following code
```js
// @/plugins/fbq-events.js
export default async ({ app, route, req }) => {
  if (process.client) {
    const scope = effectScope()
    extendScopeContext(scope, app)
    const { $fb } = app

    await scope.run(async () => {
      const { intercept } = useIntercept()
      const { cartItems, totalPrice } = useCart()

        intercept("addToCart", (props) => {
          console.debug("added")
          const { product, quantity } = props
          $fb.fbq("track", "AddToCart", {
            content_name: product.translated.name,
            content_type: "product",
            contents: cartItems.value.map((cartItem) => {
              return {
                id: cartItem.payload.productNumber,
                name: cartItem.label,
                quantity: cartItem.quantity,
              }
            }),
            currency: "EUR",
            value: totalPrice,
          })
        })
      }
    })
}
```

```js
//nuxt.config.js

plugins: [
    "~/plugins/fbq-events.js",
  ],
```

I tested this and it affects all my plugins but when using interceptors this is especially a big provblem because my gtag events and pixel events will be sent twice.

### Steps To Reproduce

1. Create a custom plugin

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Which element is affected?

plugins

### Environment

```markdown
- OS: macOs Big sur
- Node: 14
- Shopware API: 6.4.4.1
- Shopware PWA version: 1.0.1
```

**Comment by mmeester** [comment]
I assume the plugin is both loaded on the server- as the client-side, looking at the name of the plugin this specific plugin should only load client-side by renaming `fbq-events.js` into `fbq-events.client.js` and loading the plugin: 

``` js
//nuxt.config.js

plugins: [
    "~/plugins/fbq-events.client.js",
  ],
```

more info: https://nuxtjs.org/docs/directory-structure/plugins#client-or-server-side-only

**Comment by meeshoogendoorn** [comment]
@mmeester Already tried that but with no effect

i already tried:
- only client side
- only server side
- extending setup fucntion
- extending new scope
- load plugin in config array as last and first

I now have a very hacky solution with a sharedRef set to true when plugin is initialized.

**Comment by mmeester** [comment]
So, on client-side fbq-events get's called twice?

**Comment by meeshoogendoorn** [comment]
Yes but i checked it and it is with every plugin on load it will initialize twice.

**Comment by patzick** [comment]
hey @meeshoogendoorn 
please try this
1. make sure you have this plugin under `src/plugins/` directory
2. do not add the plugin into nuxt.config file - it should be registered automatically then

let me know if this works for you :)

**Comment by mkucmus** [comment]
@meeshoogendoorn sorry for hiding the information that we autoload every plugin located in `src/plugins` directory 🙏🏻 

a tiny tip from our team: please use [on](https://github.com/vuestorefront/shopware-pwa/blob/master/packages/composables/src/logic/useIntercept.ts#L201) instead of `intercept` method from `useIntercept` composable. Thanks to this your interceptor will be visible within dedicated Shopware PWA tab in Vue dev tools as its in the screen below: 💪🏻

![image](https://user-images.githubusercontent.com/5596960/144265082-413edae3-10f9-403a-a48a-ec36c1c4cb7b.png)

![image](https://user-images.githubusercontent.com/5596960/144265261-b780ed13-a248-4296-aa02-0f3652019bea.png)

**Comment by meeshoogendoorn** [comment]
@mkucmus  I was using that but lot was throwing errors in development i think so then i removed it and now i still have to migrate the events.

@patzick Thanks for the solution. It worked 👍 

Maybe this is something to notify in the docs or did i just didn't see that sentence.

**Comment by niklaswolf** [comment]
@patzick @mkucmus wow that's something no nuxt-developer would asume :D 
What are the reasons that you're doing this, I would actually opt for removing this autoload (at least for custom modules), as it's really counter-intuitive, if there aren't any good reasons...

**Comment by niklaswolf** [comment]
Adding this: apparently the autoloading only works for JS-Files, we also have some TS-Files, which don't get autoloaded...

**Comment by patzick** [comment]
@niklaswolf, these are reasonable arguments. I believe we can find some good solutions here.
The pure Nuxt way is to register plugins manually inside the `/plugins` directory. We're registering those from `/src/plugins`, which is a bit different. I agree this might be unclear, but it also gives the possibility to add custom plugins from the theme.

My proposition of compromise:
1. Add `.ts` files support for autoloading plugins
2. Add section inside docs, explaining two ways of adding a plugin. The recommended way would be to keep them inside the `root` directory, not in `src` and register them manually.
3. Add `warnings` for plugin files registered automatically, so it's visible what's going on

Does this sound good to you? :)

**Comment by niklaswolf** [comment]
@patzick this sounds good yeah :)
I'd also add a comment in `src/plugins/Readme.md` to make it clear, that these plugins get auto loaded and if this is not intended one could use `root/plugins` and register them manually

**Comment by meeshoogendoorn** [comment]
I got something to add. In the docs in the section about intercepting events. 
See the following url: [https://shopware-pwa-docs.vuestorefront.io/landing/concepts/interceptor.html#usage-examples](https://shopware-pwa-docs.vuestorefront.io/landing/concepts/interceptor.html#usage-examples)

Here u write something about a nuxt plugin but here u also say to register the plugin in nuxt.config.js. When we will do that it will also register the plugin twice right and listen to events twice.


# See following content:

### In Nuxt plugin

If you don't want to change any component in order to react on some event, you can create new Nuxt plugin, for example, `src/plugins/my-interceptors.js`, add it to `nuxt.config.js` file:

```
  /*
   ** Plugins to load before mounting the App
   ** https://nuxtjs.org/guide/plugins
   */
  plugins: ['~/plugins/my-interceptor.js'],
```

and then inside this file, you can use interceptors directly like this (it will be also useful for intercepting your own events)


coming from this file: [file](https://github.com/vuestorefront/shopware-pwa/blob/bed01996339016fe32c985e82eb334d27ebc6a29/docs/landing/concepts/interceptor.md)
