### ISSUE TITLE
[Bug] Cannot read property 'pathPrefix' of undefined

### ISSUE THREAD

**Issue by mmeester** [vuestorefront/shopware-pwa#1750]
### What happened?

Running a fresh install of the latest (1.1.0) results in the following error:

`Cannot read property 'pathPrefix' of undefined` 

### Steps To Reproduce

1. Clean install of shopware-pwa using `npx @shopware-pwa/cli init`
2. Clean install of Shopware production template `v6.4.6.1` => shopware/production
3. fetch domains `npx @shopware-pwa/cli domains` => domains.json is created and set correctly
4. Run `npm run dev` or `yarn dev`
5. Open in browser, open console and the error appears

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Which element is affected?

nuxt-module

### Environment

```markdown
- OS: macOs
- Node: 14
- Shopware API: 6.4.6.1
- Shopware PWA version: 1.1.0 (assuming we're talking about `@shopware-pwa/nuxt-module`)
```

**Comment by mmeester** [comment]
@mkucmus I've created a pr as well to have this fixed

**Comment by mmeester** [comment]
I'm not sure why some of the checks are failing btw?

**Comment by mkucmus** [comment]
> I'm not sure why some of the checks are failing btw?

Don't worry, the publishing step is failing due to not having credentials for our docker registry :) the previous steps are fine - it's enough here. We need to do some additional checks manually in this case 👍🏻

**Comment by manuelschroederdev** [comment]
I'm getting the same error (Also on macOS using node 14).

**Comment by mmeester** [comment]
@manuelschroederdev you can edit domain.js as created in the pr yourself if you want to continue dev-ing for now

**Comment by manuelschroederdev** [comment]
@mmeester Perfect, thanks a lot for the quick fix and pr!
