### ISSUE TITLE
[Bug]  useCms product associations not working

### ISSUE THREAD

**Issue by stigvanbrabant** [vuestorefront/shopware-pwa#1759]
### What happened?

I want to adapt associations of the listing page, so i have access to all images of a product and also its properties. I was able to make it work after pagination as then it uses a different endpoint and other defaults. But on refresh (when it gets its data from the cms as the initialListing) nothing is working.

My useCms associations:
```
associations: {
  manufacturer: {
    associations: {
      media: {},
    },
  },
  media: {
    sort: [
      {
        field: 'position',
        order: 'ASC',
        naturalSorting: false,
      },
    ],
  },
  productReviews: {},
  properties: {
    associations: {
      group: {},
    },
  },
},
```

My useListing associations:
```
associations: {
  media: {
    sort: [
      {
        field: 'position',
        order: 'ASC',
        naturalSorting: false,
      },
    ],
  },
  properties: {
    associations: {
      group: {},
    },
  },
},
```

Is there something i'm doing wrong maybe? I'm not too familiar with the store api so it could be i'm missing something.

### Steps To Reproduce

1. Try to overwrite default for listing page
2. Refresh and adaptions are not coming through
3. Paginate and everything works as expected

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Which element is affected?

composables

### Environment

```markdown
- OS: macOS
- Node: 14.x
- Shopware API: 6.4.2.1
- Shopware PWA version: 1.0.1
```

**Comment by mkucmus** [comment]
Hi @stigvanbrabant!
thanks for being alert. The issue was probably caused bu the problem with images in core API itself. Happily, It was fixed with the Shopware v6.4.7.0 version. Please upgrade you Shopware 6 instance if it's possible 👍🏻

**Comment by mkucmus** [comment]
Hello @stigvanbrabant. The reason why the associations for product don't work in page resolver endpoint is the different context. 
Currently, page resolver's response may have many of entities, and each one have its own context, and possible filters, associations that can be used. This is why it's not possible to pass association "properties" parameter to the request and get the expected result. Page resolver just can't recognize what entity it's used for (got categories and products and other entities as well). The product-listing context is clear and it's about only a product as a main entity.

The correct context on what associations and filtering can be used with is `cmsPage` (not a product). 

Maybe it's a good point to start a discussion on the problem. For instance, we could add prefixes to the associations that can group the parameters by the entity type to have sth like:
```
associations: {
"product.properties": {} // tell the page resolver that we need properties associations on product entity if any exists 
}
```
nevertheless, the problem and the solution must be discussed deeply in the wider group 👩🏻 👨🏻 

Leave a comment please on what you think 🙏🏻 👍🏻

**Comment by stigvanbrabant** [comment]
@mkucmus Yeah this seems like a decent solution to me, certainly would fix the problem that i'm having. So it's actually not currently possible to achieve what i'm trying to do?

**Comment by mkucmus** [comment]
> @mkucmus Yeah this seems like a decent solution to me, certainly would fix the problem that i'm having. So it's actually not currently possible to achieve what i'm trying to do?

So far, "mixing" associations' context would be possible only programmatic way, like overriding the PWA plugin's logic. I can't see any other solutions on that. But... let's ask @elkmod what he thinks first :)

**Comment by mkucmus** [comment]
I'm closing the issue, because the requests' handling should be managed on API side. It's recommended to move discussion on https://github.com/shopware/platform repository or https://github.com/elkmod/SwagShopwarePwa
