### ISSUE TITLE
[FEATURE] Filter products by IDs

### ISSUE THREAD

**Issue by IndeedEvan** [vuestorefront/shopware-pwa#1773]
### Description

Be able to filter products by IDs (programmatically) in the initial listing the same way we can filter products when using the search composable.

### Acceptance criteria

- getElements from useListing() return only products figuring in the product IDs array sent in setInitialListing

### Infos

![structure](https://user-images.githubusercontent.com/12630507/147766853-22fca3f6-fa5d-442f-94d7-2194a2e2bb5c.jpg)

In my project I have a custom API that return product IDs available for a specific date + manufacturer ID from Shopware (logic in this API is very complex so I prefered not doing a Shopware plugin for that). I tried using the search methods, it worked fine but I want to keep the product/category routing mechanism. I also tried removing products inside getElements but it's dirty and it breaks pagination. Is there a way of doing this without touching to actual version or am I missing something ? 

Thank you for your amazing work 👍 💯

**Comment by mkucmus** [comment]
hi @IndeedEvan, thanks! Maybe I don't get it, but would it work for you if you use just a  store-api's search criteria to filter it on the request/response layer? Search parameters have something like "ids" parameter, described here: https://github.com/vuestorefront/shopware-pwa/blob/feat/wishlist-service/packages/commons/interfaces/search/SearchCriteria.ts#L69

you could use it and don't lose the pagination in the second call in page resolver/ product listing requests.

**Comment by IndeedEvan** [comment]
I tried doing this on the search page, it worked fine but the parameter "query" is mandatory for Shopware, in my case on don't want to display products depending on a specific word match.

```Javascript
[search] Problem with initial search {
  messages: [
    {
      status: '400',
      code: 'FRAMEWORK__MISSING_REQUEST_PARAMETER',
      title: 'Bad Request',
      detail: 'Parameter "search" is missing.',
      meta: [Object]
    }
  ],
  statusCode: 400
}
```

**Comment by mkucmus** [comment]
🤔 what about `/store-api/product` endpoint?  it would go like:

![image](https://user-images.githubusercontent.com/5596960/147812222-b20c9fa1-e90c-43f5-9fda-1820269d1c81.png)

here's the request in curl format to try out locally:
```
curl --location --request POST 'https://pwa-demo-api.shopware.com/trunk/store-api/product' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json, text/plain, */*' \
--header 'sw-access-key: SWSC40-LJTNO6COUEN7CJMXKLA' \
--data-raw '{
    "ids": ["001c11fe07274f7da46240e6655e0cab"]
}'
```

or if you have a categoryId you could use a product-listing endpoint and have all the additional listing info:
![image](https://user-images.githubusercontent.com/5596960/147812161-e5a09ebb-5229-4eb7-b6db-e5ddb6036627.png)

**Comment by IndeedEvan** [comment]
Ok thanks for that answer. So i'm going to call directly the API through axios, or I can use apiInstance from the getApplicationContext composable ?

**Comment by IndeedEvan** [comment]
Found it ! Thanks again, closing the issue.

```Javascript
export declare interface ShopwareApiInstance {
    onConfigChange: (fn: (context: ConfigChangedArgs) => void) => void;
    config: ClientSettings;
    setup: (config?: ClientSettings) => void;
    update: (config?: ClientSettings) => void;
    invoke: {
        post: AxiosInstance["post"];
        get: AxiosInstance["get"];
        put: AxiosInstance["put"];
        patch: AxiosInstance["patch"];
        delete: AxiosInstance["delete"];
    };
    defaults: AxiosInstance["defaults"];
    /**
     * We expose axios instance for advanced use. You might cause some side effects, use with caution.
     */
    _axiosInstance: AxiosInstance;
}
```

**Comment by mkucmus** [comment]
Glad to see it 👍🏻 
alternatively you can utilize `getProducts` method from `@shopware-pwa/shopware-6-client` package 👍🏻 
https://shopware-pwa-docs.vuestorefront.io/landing/resources/api/shopware-6-client.getproducts.html

**Comment by IndeedEvan** [comment]
Yes I tried something like that before, but it doesn't return a nice product listing :

```Javascript
import { getProducts } from "@shopware-pwa/shopware-6-client"

...

const { apiInstance } = getApplicationContext({ contextName: 'useProduct' })

    const products = ref([]);
 
    (async () => {
      const res = await root.context.$mpm.get('/products/1/2022-01-01') //My API

      let params = {
        ids: res.data
      }

      products.value = await getProducts(params, apiInstance);
    })()

    console.log(products)

```

Just saw this tho

```Javascript
/**
 * Get default amount of products and listing configuration for given category
 *
 * @throws ClientApiError
 * @public
 */
export async function getCategoryProducts(
  categoryId: string,
  criteria?: ShopwareSearchParams,
  contextInstance: ShopwareApiInstance = defaultInstance
): Promise<ProductListingResult> {
  const resp = await contextInstance.invoke.post(
    `${getProductListingEndpoint(categoryId)}`,
    criteria
  );
  return resp.data;
}
```

It will hit `/store-api/product-listing/${categoryId}`
