### ISSUE TITLE
[Bug] Double-Click link CMS Page loading issue

### ISSUE THREAD

**Issue by TheGoobsy** [vuestorefront/shopware-pwa#1775]
### What happened?

- When double-clicking a link, which results in a route change, the CMS Elements are not being loaded correctly.
- e.g. when double clicking a link changing from route `/` to `/JEANS`, the CMS Element for `/` is still being displayed.
- Changing with a double-click to `/KIDS`, displays the CMS Element for `/JEANS`. The url updates, but not the content.

### My analysis so far

In the `src/pages/_.vue` file the values for the `page`, `cmsPage`. `staticPage` (...) refs are not correct after double-clicking a link when the setup() for the DynamicRoute component is being called, which leads to the wrong CMS Element being displayed. Using computed recognises the changes, but it breaks the product-listing and still often displays the wrong content, and also results in Elements loading multiple times.

It somehow does work correctly on https://shopware-pwa.storefrontcloud.io (Edit: Just tested it again, and it now happens every time I double click a link in the navigation), but I'm always getting this issue on my local shopware-pwa instance. I tried pwa v1.1.0 and v1.2.0, using my local shopware backend and also [https://pwa-demo-api.shopware.com/trunk](https://pwa-demo-api.shopware.com/trunk)

### Steps To Reproduce

- Install shopware-pwa using the latest (v1.2.0) version, using https://pwa-demo-api.shopware.com/trunk as the backend
- build production (or dev) with `yarn build` + `yarn start`
- Start on the start-page (e.g. `localhost:3000/`)
- Double-click `JEANS` in the navigation (leads to `localhost:3000/JEANS`)
- Double-click the Home-Icon next to `JEANS` in the navigation (leads back to `localhost:3000/`) 
- Notice how the CMS Elements on the page changes

### Expected result: 
- When double-clicking `JEANS`, the product-listing for Jeans should be displayed
- When double-clicking the home-icon, the start page should be displayed

### Actual result:
- When double-clicking `JEANS`, the start-page CMS Element is still being displayed (or the last visited page)
- When double clicking the home-icon, it now displays the product-listing for `JEANS`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Which element is affected?

composables

### Environment

```markdown
- OS: Linux
- Node: 14.18.1
- Shopware API: 6.4.6.1
- Shopware PWA version: 1.2.0 and 1.1.0
```

**Comment by petritz** [comment]
I have the same issue, any news on this issue? @mkucmus

**Comment by TheGoobsy** [comment]
Is there any chance that this issue will be resolved in the near future? :eyes: 
It's been over a year now...
