### ISSUE TITLE
[FEATURE] NodeJS 17 support

### ISSUE THREAD

**Issue by shyim** [vuestorefront/shopware-pwa#1778]
### Description

error shopware-pwa-project@1.0.0: The engine "node" is incompatible with this module. Expected version ">=14.15.3 <=16.13.1". Got "17.3.0"
error Found incompatible module.

**Comment by mkucmus** [comment]
Hi @shyim! I've tested our stack being on node v17 and everything work as expected but only if the special flag for NODE is set before building time (via env in our case). 
here's a relevant change: https://github.com/vuestorefront/shopware-pwa/pull/1782/files#diff-4ab57027f9d4682ead6b00cca3034f7355f13270091bcf4d8f0dbe5d1599528dR427

```
NODE_OPTIONS=--openssl-legacy-provider
```

details on webpack as a part of nuxt.js causing the problem: https://github.com/webpack/webpack/issues/14532

**Comment by bitfactory-frank-spee** [comment]
@mkucmus Is there any news on Node.js 17 support ? Which is not an LTS, so v18 and so also Nuxt 2.16.x is better. I started a discussion here: https://github.com/vuestorefront/shopware-pwa/discussions/1988 to get some information.
