### ISSUE TITLE
[Bug] Create theme command

### ISSUE THREAD

**Issue by Maximilian-Schwarz** [vuestorefront/shopware-pwa#1784]
### What happened?

If i setup a new project with:
`npx @shopware-pwa/clie init`

After the setup the following command to create a new theme:
`npx @shopware-pwa/cli create-theme`

I answer the questions:
Type a name for your theme: default-blank
Which theme you'd like to extend: @shopware-pwa/default-theme

After the last question i got the following error:
![Bildschirmfoto 2022-01-11 um 17 39 35](https://user-images.githubusercontent.com/63093230/149093399-c1eb0299-e2bf-4913-b8ec-aee51c575caf.png)

Any ideas? Did i anything wrong?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Which element is affected?

CLI

### Environment

```markdown
- OS: macOS
- Node: 14
- Shopware API: v6.4.7.0
- Shopware PWA version: 1.3.0
```

### Relevant log output

```shell
/Users/uniqueweb/.npm/_npx/1319/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Command failed with exit code 1: yarn run init -y
    at makeError (/Users/uniqueweb/.npm/_npx/1319/lib/node_modules/@shopware-pwa/cli/build/commands/create-theme.js:1088:17)
    at handlePromise (/Users/uniqueweb/.npm/_npx/1319/lib/node_modules/@shopware-pwa/cli/build/commands/create-theme.js:2050:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Command.run (/Users/uniqueweb/.npm/_npx/1319/lib/node_modules/@shopware-pwa/cli/build/commands/create-theme.js:2246:5) {
  command: 'yarn run init -y',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn run v1.22.17\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.',
  stderr: 'warning ../../package.json: No license field\n' +
    'error Command "init" not found.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by patzick** [comment]
thank you very much, you should be able to invoke this command using canary version
```
npx @shopware-pwa/cli@canary create-theme
```
it will be released with the next stable version :)
