### ISSUE TITLE
handlePayment return error

### ISSUE THREAD

**Issue by amin212121** [vuestorefront/shopware-pwa#1799]
### What happened?

Hey guys, when I call handlePayment(order.id) with GOOGLE PAY (stripe) I always receive this type of error. Someone know how fix it? I tried find some info in docs but nothing.
![image](https://user-images.githubusercontent.com/36712833/151146622-ea0105ee-b8cb-4709-b643-ca9ce70195ed.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Environment

```markdown
- OS: 
- Node: 
- Shopware API: 
- Shopware PWA version:
```

**Comment by mkucmus** [comment]
hi @amin212121. The error comes from API and that is the place I would start debugging. Maybe you can find some clues on why is that in the official documentation of the plugin.

Perhaps there is some missing data passed to the handle payment method. 

We can have a look if you provide more details:
- Shopware PWA version
- Shopware 6 exact version
- plugin source and some details

**Comment by amin212121** [comment]
> hi @amin212121. The error comes from API and that is the place I would start debugging. Maybe you can find some clues on why is that in the official documentation of the plugin.
> 
> Perhaps there is some missing data passed to the handle payment method.
> 
> We can have a look if you provide more details:
> 
> * Shopware PWA version
> * Shopware 6 exact version
> * plugin source and some details

@mkucmus 
1) I use my custom front-end solution but with "@shopware-pwa/shopware-6-client" version is ^1.3.0
2) v6.4.7.0 Stable Version
3) Stripe Payment Version: 1.8.0

I have read docs of the plugin "Stripe Payment" but there ain't mention any word about "How work with headless solution", here is ref for official docs https://docs.google.com/document/d/1qGa_hcoPBq_XkSmfq4GMLJMkFaQz7-w3jdn5DJilJVo/edit

**Comment by amin212121** [comment]
@mkucmus any update here?

**Comment by mkucmus** [comment]
@amin212121 I will check it willingly, but first I have to precise what exactly plugin it is, because I can see the Strip Payment plugin https://store.shopware.com/en/cwb01476m/stripe-payment-plugin.html only for v5.x of Shopware platform. 
Could you send me a direct link to the plugin?

**Comment by mkucmus** [comment]
Ok, I'm back with some details from my investigation. What I found is:
- being on Shopware PWA - you need to implement a frontend component to save/keep credit card data - as a presentation layer only
- the frontend component, when you are creating a payment intent (see docs in stripe) receives the unique token that should be used in further step
- `handlePayment` method which is being called after the order is created accepts the additional data, like taken from step above to inform the payment plugin, that the payment process has started (credit card has been checked or money was reserverd) and amount can be captured on the backend -> if does work - show success page.

By default, the Stripe plugin you've provided, does not have any frontend part for PWA which can handle the described flow. so additional parameters are missing. 

you can track the required data that can be used in the PWA as well in the standard Storefront to see how it works:
![image](https://user-images.githubusercontent.com/5596960/156186040-49cb06ec-f92c-457c-bbce-e5c1676e91fd.png)
in the picture we can see the endpoint being called after placing an order `/finalize-transaction` (equivalent of handle-payment used in Shopware PWA). In the payload there are two extra parameters: payment token and intent client token -> I can only guess, but It looks like those things are missing in your project in handle payment request.

**Comment by mkucmus** [comment]
I'm closing the issue because the payment plugin is not ready to handle the API calls to manage payment processes. 
Additional work on plugin's side is required.
