### ISSUE TITLE
[Bug] changing language from English -> Deutsch ->English , does nothing

### ISSUE THREAD

**Issue by akshaynikhare** [vuestorefront/shopware-pwa#1819]
### What happened?

on  https://shopware-pwa.storefrontcloud.io/

when we change the language from  English -> Deutsch, everything works and the website translates and URL updates 
but when Switching the language back from Deutsch ->English, the URL updates but not the translation 
![image](https://user-images.githubusercontent.com/9725336/154461598-2ca0d71e-fd24-4893-b7ef-28d7339b67b4.png)

### Steps To Reproduce

1. go to any PWA storefront in my case https://shopware-pwa.storefrontcloud.io/
2. switch change the language from English -> Deutsch
3. then again change back to English , From Deutsch ->English 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Canary (generated by CLI)

### Which element is affected?

default-theme, theme-base

### Environment

```markdown
- OS: Ubuntu 20.04.1 , 5.10.16.3-microsoft-standard-WSL2
- Node: 16.13.1
- Shopware API: 6.4.8.0
- Shopware PWA version: 1.3.1-canary
```

**Comment by mkucmus** [comment]
Hi @akshaynikhare! thanks for reporting 💪🏻 
The issue has been probably fixed and it's waiting for the next release. Visit https://shopware-pwa-canary.storefrontcloud.io which points to the master branch and it's most recent. Leave your feedback on how it works please 🙏🏻
