### ISSUE TITLE
[Bug] Grammer in Readme

### ISSUE THREAD

**Issue by casdep** [vuestorefront/shopware-pwa#1837]
### What happened?

In the README.md > https://github.com/vuestorefront/shopware-pwa#readme

Under: Quickstart >> Usage >> It will ask for the address to yous shopware instance,...
Should be:
It will ask for the address to your shopware instance. Where yous should be your.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Environment

```markdown
- OS: 
- Node: 
- Shopware API: 
- Shopware PWA version:
```

**Comment by LoftyDroid** [comment]
hey @casdep can you assign this to me? I would like to contribute to this repo.
