### ISSUE TITLE
[FEATURE] service menu

### ISSUE THREAD

**Issue by mkucmus** [vuestorefront/shopware-pwa#1890]
Service menu is one of available menu types. Can be fetched via store-api under `service-menu` and represents the useful information like: contact, phone number and other support stuff. 

Acceptance criteria
- [ ] store-api documentation is read to have a basic knowledge how it works: https://shopware.stoplight.io/docs/store-api/b3A6ODI2NTY3MQ-fetch-a-navigation-menu
- [ ] `useNavigation` composable is used to fetch `service-menu` predefined type of navigation
- [ ] additional component is created to represent the information fetched from API regarding service menu
- [ ] design: can follow the standard storefront display

**Comment by quando1910** [comment]
I take a look at this page https://pwa-demo-api.shopware.com/trunk/
and see the service menu belongs to Footer, so we will add it into Footer for PWA, is it correct?
and does the design similar to the below image?
<img width="305" alt="Screen Shot 2022-06-07 at 5 10 12 PM" src="https://user-images.githubusercontent.com/29194019/172355191-95361096-82ef-421d-8bdd-e713ac2010dd.png">

**Comment by mkucmus** [comment]
yes @quando1910, please add service menu to the footer.
you can find how to setup service navigation and see what it looks like: https://docs.shopware.com/en/shopware-6-en/tutorials-and-faq/basic-setup
