### ISSUE TITLE
[Bug] sharedStore is not injected into Vue instance

### ISSUE THREAD

**Issue by super-kamil** [vuestorefront/shopware-pwa#1910]
### What happened?

The latest (1.5.1) release is unusable. After clean installation, the app does not start.

![image](https://user-images.githubusercontent.com/708028/177002021-05318656-ad56-4224-862e-d578f6c7ce75.png)

### Steps To Reproduce

1. Setup new app with `npx @shopware-pwa/cli init`
2. Run `yarn dev`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Which element is affected?

composables

### Environment

```markdown
- OS: Win11
- Node: 14.19.0
```

**Comment by super-kamil** [comment]
```
 WARN  [getApplicationContext] Use createShopware method to setup composables.
 WARN  [useBreadcrumbs] Use createShopware method to setup composables.
 WARN  [useSharedState] Use createShopware method to setup composables. 
 ```

**Comment by super-kamil** [comment]
Unfortunately, I'm totally blocked now by this. 

I tried many things. Installed on a Linux env. 

What is strange, even if I install 1.4.0 I get the same error.

**Comment by mkucmus** [comment]
Some dependency enforces to use vue at version 2.7.0 in the project and it's been not tested yet, so we had some problems and need to make a migration according to the migration guide of 2.7.x  itself. 

It's recommended to reinit a project after the 1.5.2 is released (tomorrow probably), or do it manually by adding a `resolutions` section in your package.json, as it's done here: https://github.com/vuestorefront/shopware-pwa/pull/1912/files#diff-fed5090dfd20306052054c7ead52a4bd2066b4e42f742c866841be53368cc9a7

we will keep you updated when we are up to date with the latest release of vue core packages, then the resolutions section won't be needed anymore 👍🏻

**Comment by super-kamil** [comment]
works, thanks
