### ISSUE TITLE
::v-deep usage as a combinator has been deprecated

### ISSUE THREAD

**Issue by super-kamil** [vuestorefront/shopware-pwa#1911]
### What happened?

After starting `yarn dev` the console is full of warnings

`WARN  [@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.`

### Steps To Reproduce

1. npx @shopware-pwa/cli init
2. yarn dev

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Which element is affected?

default-theme

### Environment

```markdown
- OS: Win11
- Node: 14.19.0
```

**Comment by mkucmus** [comment]
The issue is connected to v2.7.0 of vue core packages which is not supported yet in project.
