### ISSUE TITLE
[FEATURE] Remove hardcoded Google Fonts

### ISSUE THREAD

**Issue by bow-sb** [vuestorefront/shopware-pwa#1945]
### Description

A German court has ruled that Google Fonts are not GDPR compliant. It would be better to remove the hardcoded inclusion and add a notice to the installation instructions, the same way [Storefront UI](https://docs.storefrontui.io/?path=/docs/getting-started-installation--page#install-custom-font) handles it currently.

[Court decision (German)](https://www.gesetze-bayern.de/Content/Document/Y-300-Z-GRURRS-B-2022-N-612?hl=true)
[Article about Google Fonts (English)](https://usercentrics.com/knowledge-hub/google-fonts-gdpr-compliant/)

### Acceptance criteria

- [ ] Remove Google Fonts from project
- [ ] Add instructions for usage to docs

**Comment by super-kamil** [comment]
Here is a workaround for this until it gets removed:

nuxt.config.js
```js
import extendNuxtConfig from "@shopware-pwa/nuxt-module/config";
const defaultConfig = extendNuxtConfig();

// remove default fonts Raleway and Roboto
defaultConfig.head.link = defaultConfig.head.link.filter((link) => {
  return !(
    link.href &&
    (link.href.includes("Roboto") || link.href.includes("Raleway"))
  );
});
```

This can be applied to Google Fonts as well.
