### ISSUE TITLE
[Bug] Can't add new address

### ISSUE THREAD

**Issue by super-kamil** [vuestorefront/shopware-pwa#1968]
### What happened?

![image](https://user-images.githubusercontent.com/708028/202158106-b209d575-cea9-45e3-9467-1fdf803e74cd.png)

### Steps To Reproduce

1. Go to checkout
2. Click on "Add address"
3. Fill in data

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Canary (generated by CLI)

**Comment by super-kamil** [comment]
Looks like there is a new version in master branch. But without a release, we can't use it. Also editing the address is now gone.

**Comment by patzick** [comment]
hey @super-kamil, you can always use version from master branch, it's tagged on `npm` as `canary`, so every PR merged has it's own version. You can point to specific canary version to avoid some unplanned upgrades f.ex current canary is `1.5.4-canary.1703`. You can check package versions here: https://www.npmjs.com/package/@shopware-pwa/composables?activeTab=versions
