### ISSUE TITLE
[Bug] Error after building demo project

### ISSUE THREAD

**Issue by KalleJoP** [vuestorefront/shopware-pwa#1971]
### What happened?

I get an error after building the demo project.. 
<img width="1378" alt="Bildschirm­foto 2022-12-06 um 17 29 09" src="https://user-images.githubusercontent.com/61844416/205968023-3d8fe85c-ad45-46c4-ba80-d03820367408.png">

I installed shopware pwa with this instruction: https://shopware-pwa-docs.vuestorefront.io/landing/resources/cheatsheet.html#installation

Thanks for help😃

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Canary (generated by CLI)

### Environment

```markdown
- OS: macOS m2 Chip
- Node: 14.21.1
- Shopware API: latest
- Shopware PWA version: latest
```

### Relevant log output

```shell
Must use import to load ES Module: /Users/paeplow/Developer/private_stuff/clotho_pwa/node_modules/@glidejs/glide/dist/glide.js require() of ES modules is not supported. require() of /Users/paeplow/Developer/private_stuff/clotho_pwa/node_modules/@glidejs/glide/dist/glide.js from /Users/paeplow/Developer/private_stuff/clotho_pwa/node_modules/vue-server-renderer/build.dev.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename glide.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/paeplow/Developer/private_stuff/clotho_pwa/node_modules/@glidejs/glide/package.json.
```

**Comment by KalleJoP** [comment]
I don´t know how, but I got it working. I changed the ownership of some folders which belongs to node in /usr/local and now it works.

**Comment by martinSternelius** [comment]
> I don´t know how, but I got it working. I changed the ownership of some folders which belongs to node in /usr/local and now it works.

Hi, I'm having this exact problem as well. Could you give more detail as to how you solved it?

**Comment by KalleJoP** [comment]
Sorry for the late response. I don´t know exactly which action fixed the issue, but I changed the ownership to my user for everything in /usr/local, I delete the node_modules folder in /usr/local/lib and use node version v14.17.0. After these steps, I did this setup: https://shopware-pwa-docs.vuestorefront.io/landing/resources/cheatsheet.html#installation. I hope it helps you. 😃



This is my /usr/local now: 
<img width="567" alt="Bildschirm­foto 2022-12-14 um 14 35 31" src="https://user-images.githubusercontent.com/61844416/207609242-d4a58745-b759-4f71-a82e-85160978e856.png">

**Comment by SenseiDanielosan** [comment]
> Hi, I'm having this exact problem as well. Could you give more detail as to how you solved it?

Hey, I solved this issue by running `yarn` and then `yarn build --types`. After that I was able to access the PWA.

https://shopware-pwa-docs.vuestorefront.io/landing/resources/cheatsheet.html#installation

**Comment by SenseiDanielosan** [comment]
> I don't know how you guys fixed the problem, but after the commit [glidejs/glide@5b8bfe5](https://github.com/glidejs/glide/commit/5b8bfe52e2c4ebd4eda2a1f9d811228e527904ff) it is not possible for me to run the project without the error. No matter which node version i use, always the same error appears 🤷

So did you try to reinstall the node_modules? After that try the commands I wrote above.
I use node version 14.17.0 and everything works as it should.
