### ISSUE TITLE
[FEATURE]Home page -add main categories buttons under the header on mobile

### ISSUE THREAD

**Issue by akrajna** [vuestorefront/shopware-pwa#399]
Related to the issue #391 

**Describe how this feature will help us improve**
Better visual reception, easier website navigation

**Describe the solution you'd considered**
Add categories buttons under the header on mobile as below:
<img width="162" alt="CategoryButtons" src="https://user-images.githubusercontent.com/57936972/74650055-23b64400-5181-11ea-9d90-2e1513fa6194.png">

After pressing button with one main category a list of categories appears as below:
<img width="160" alt="categories" src="https://user-images.githubusercontent.com/57936972/74650315-b35bf280-5181-11ea-9099-a3df261dd197.png">

After selectin category a list of subcategories appear as below:
<img width="163" alt="subcategories" src="https://user-images.githubusercontent.com/57936972/74650389-e605eb00-5181-11ea-8055-dbd6c3f15a77.png">

**Acceptance criteria**

- [ ] categories buttons are added under the header on home page
- [ ] after pressing chosen button of categories a list of subcategories appears
- [ ]  after pressing one of the subcategories user is redirected to the chosen category
- [ ] after pressing the back arrow on the top of the list user is going one step back (at the end the list is closing)

**Comment by patzick** [comment]
@akrajna is it still on designs after their change?

**Comment by akrajna** [comment]
On the new design it still exists but looks different, as below:
<img width="182" alt="MobileHome" src="https://user-images.githubusercontent.com/57936972/82194875-cb195300-98f7-11ea-99e9-8a7ccc393698.png">
