### ISSUE TITLE
[FEATURE] Add popup after adding to cart on mobile

### ISSUE THREAD

**Issue by akrajna** [vuestorefront/shopware-pwa#407]
**Describe how this feature will help us improve**
User will be sure that his action 'add to cart' was successfully completed

**Describe the solution you'd considered**
On mobile - add popup window with information 'Size ... was added to your shopping bag' after adding product to the cart as below:

![AddToCartInfo](https://user-images.githubusercontent.com/57936972/74733793-61809e80-524d-11ea-92de-74e9d71ff406.gif)

**Acceptance criteria**

- [ ]  the popup appears after user adds product to the cart

**Comment by pspaczek** [comment]
@akrajna can you add Feature issues at Storefront UI?

**Comment by patzick** [comment]
@akrajna please add issue as Przemek suggested and link it here

**Comment by akrajna** [comment]
related issue https://github.com/DivanteLtd/storefront-ui/issues/1196
