### ISSUE TITLE
I want to see CMS content and image in Mega Menu

### ISSUE THREAD

**Issue by rmakara** [vuestorefront/shopware-pwa#427]
**Context**
In https://github.com/DivanteLtd/shopware-pwa/issues/8 we delivered the mega menu. Now we want to let the administrator customize its look by adding images and CMS content.

**Blocked by:**
* #8 

**Acceptance Criteria**
* I can define custom text, which is visible in mega menu.
* I can define an image, which is visible in mega menu.

**Comment by patzick** [comment]
this is to discuss how we could handle it using categories and layouts
