### ISSUE TITLE
[BUG] Order can be placed without agreeing to T&C

### ISSUE THREAD

**Issue by elkmod** [vuestorefront/shopware-pwa#772]
### Describe the bug

An order can be placed without clicking the T&C checkbox

### Additional context
![image](https://user-images.githubusercontent.com/7780750/82653590-bd2d4000-9c1f-11ea-9b54-12a85d10a006.png)

**Comment by luklus** [comment]
@elkmod Is the problem still present? Unfortunately I can't reproduce the bug, could You please provide additional instructions? Is this a bug or feature to add because checkbox does not currently exist.

**Comment by elkmod** [comment]
Hi @luklus, it seems that the button has been removed at some point. However, I think it should be included since it's necessary for any merchant to work with. @patzick do you know where it went?
