### ISSUE TITLE
[BUG]  WARN  Cannot stringify POJOs with symbolic keys Symbol(vfa.key.accessControlIdentifier)

### ISSUE THREAD

**Issue by ivosanchez** [vuestorefront/shopware-pwa#777]
index page, products and images dont show up on vsf 
after server initialization there is this warning on console:

 WARN  Cannot stringify POJOs with symbolic keys Symbol(vfa.key.accessControlIdentifier)
 
running sw 6.2  locally on catalina & stable version of vsf pwa 
with no plugins installed other than the vsf pwa one

**Comment by patzick** [comment]
hey @ivosanchez 
Sorry, the stable version is compatible with 6.1 at this moment. For 6.2 you should go with `canary`. We have few more polishing stuff to make, so the stable version will be compatible with 6.2 in a couple of days :)
You can track progress of that in 0.1.0 milestone here: https://github.com/DivanteLtd/shopware-pwa/milestone/4

So it's not an actual bug. Let me know if it's enough information for you. Cheers :)

**Comment by ivosanchez** [comment]
yes, thank you for letting me know. ;) 
I stared using the stable release bc I can't get through an error I get while trying to install Canary. 
I will show you in a different post. 
thanks again.
