### ISSUE TITLE
Move OrderDetails logic from setup into separate composable

### ISSUE THREAD

**Issue by mkucmus** [vuestorefront/shopware-pwa#781]
Related component: packages/default-theme/components/SwOrderDetails.vue

Acceptance criteria:
- [ ] setup as tiny as possible
- [ ] the OrderDetails composable is created
- [ ] all tests are updated

**Comment by niklaswolf** [comment]
It would also be great to have the order data broadcasted for interceptors to use it, e.g. for tracking.
The interceptor events are great for such a usecase, as you can access them from everywhere in the app, also plugins, which makes them really nice for a usecase like tracking, where you want to seperate the tracking-code as much as possible from your  app code.
