### ISSUE TITLE
[BUG]On iOS some pictures are not displayed

### ISSUE THREAD

**Issue by akrajna** [vuestorefront/shopware-pwa#811]
### Describe the bug
On demo instance on iOS some pictures are not displayed.
On home page there are no pictures at all.
On category page there are no pictures of some products.
On product page:
- distance between logo and product picture is too big
-product picture overrides the price
- in section 'Share your look' some pictures are not displayed 

### Steps to reproduce:
1. go to homepage on iOS
2. see the error
3. go to any category page
4. see the error

### Additional context
Home page:
<img width="230" alt="iOSPictures" src="https://user-images.githubusercontent.com/57936972/83117004-d412dd00-a0cc-11ea-9a4c-380d884de18a.png">
Category page:
<img width="232" alt="iOSCategoryPage" src="https://user-images.githubusercontent.com/57936972/83117158-058ba880-a0cd-11ea-9556-a4c88d2a15f1.png">
Product Page:
![iOSProductPage](https://user-images.githubusercontent.com/57936972/83117728-b98d3380-a0cd-11ea-8924-10e004f2b11b.gif)
<img width="223" alt="iOSShareYourLook" src="https://user-images.githubusercontent.com/57936972/83118013-15f05300-a0ce-11ea-8e73-e015831011b3.png">

**Comment by Rigo-m** [comment]
Picture that are not shown are in .webp format which is not yet supported in iOS
https://caniuse.com/#feat=webp
I guess this issue stands tall for other browsers as well

**Comment by patzick** [comment]
#1427 aims to solve browser compatibility images, closing this issue as the simples solution is to load proper images
