### ISSUE TITLE
[FEATURE] Implementation of 'Three columns, product boxes' block

### ISSUE THREAD

**Issue by akrajna** [vuestorefront/shopware-pwa#897]
### Description
The  'Three columns, product boxes' block is not implemented yet. 
<img width="455" alt="ThreeColumnBlockNotImplemented" src="https://user-images.githubusercontent.com/57936972/85843068-eef67100-b7a0-11ea-95b1-a09bd967e70d.png">

### Acceptance criteria

- [x] 'Three columns, product boxes' is implemented
- [x] Products in 'Three columns, product boxes' block are shown one next to another on the website
- [x] the block looks similar as in admin panel - the same order of products

**Comment by Malwurf** [comment]
I've checked that component and it should work fine.

Setting on Admin Panel:
![Screenshot from 2020-10-14 13-44-32](https://user-images.githubusercontent.com/4071200/95984475-8ac8ed00-0e23-11eb-9480-6915c92546ea.png)

How it looks  on the webpage:
![Screenshot from 2020-10-14 13-43-59](https://user-images.githubusercontent.com/4071200/95984500-95838200-0e23-11eb-8ce3-0aea601d1043.png)

**Comment by akrajna** [comment]
✔'Three columns, product boxes' is implemented
✔ Products in 'Three columns, product boxes' block are shown one next to another on the website
❌Regardless of the selected option: Layout type, Display mode, Vertical align, products are displayed on the page in the same way
<img width="446" alt="3productsOptions" src="https://user-images.githubusercontent.com/57936972/98365563-e6f1ec00-2032-11eb-8ad4-d8418edda790.png">
how it look on demo store with different types of Layout, display mode and Vertical align for each product: 
<img width="722" alt="3productsDemo" src="https://user-images.githubusercontent.com/57936972/98365787-36d0b300-2033-11eb-83bd-86499da1e964.png">
how the same configuration looks in shopware:
<img width="724" alt="3productsShopware" src="https://user-images.githubusercontent.com/57936972/98365932-77303100-2033-11eb-8ec5-834c34135b3b.png">

**Comment by patzick** [comment]
closing, for now, it can be customized when needed
