### ISSUE TITLE
[BUG] Canonical Urls

### ISSUE THREAD

**Issue by hlohaus** [vuestorefront/shopware-pwa#948]
### Describe the bug

Alternative urls should be redirected to the canonical url.

So: /old-url
to: /new-url

Also, the technical urls should redirect to the SEO urls, if they are available.

**Comment by patzick** [comment]
This is probably related to #271, that should solve your problem. WDYT @hlohaus ?

**Comment by hlohaus** [comment]
not realy

**Comment by patzick** [comment]
We've talked with @elkmod on Thursday about that and it's on the list in Priority 1. (https://github.com/DivanteLtd/shopware-pwa/projects/15#card-42738595)
We'll keep you posted!

**Comment by hlohaus** [comment]
we fixed that issue with:

https://github.com/elkmod/SwagShopwarePwa/pull/54

and   

  if (path && unwrappedPage && unwrappedPage.canonicalPathInfo) {
      if (unwrappedPage.canonicalPathInfo !== path) {
        redirect(301, app.i18n.path(unwrappedPage.canonicalPathInfo))
      }
    }

in
   pages/_lang/_.vue
