### ISSUE TITLE
[BUG]Babel safe navigation operator invalid token

### ISSUE THREAD

**Issue by Sioweb** [vuestorefront/shopware-pwa#994]
### Describe the bug

Package @shopware-pwa is using the `safe navigation operator` or `elvis operator`, and this will throw an error in my new installation.

I've fixed this for me now with `@babel/plugin-proposal-optional-chaining` and `@babel/plugin-proposal-nullish-coalescing-operator`. https://github.com/webpack/webpack/issues/10227#issue-547480527

`yarn add @babel/plugin-proposal-optional-chaining @babel/plugin-proposal-nullish-coalescing-operator --save-dev`

nuxt.config.json
```json
build: {
    extend (config, ctx) {
    },
    babel: {
      plugins: [
        ["@babel/plugin-proposal-optional-chaining"],
        ["@babel/plugin-proposal-nullish-coalescing-operator"]
      ]
    }
  }
``` 
PS.: not sure if @babel/plugin-proposal-nullish-coalescing-operator is required for the solution.

Dont now if this is a good solution, but it works for me now.

**Comment by mkucmus** [comment]
the babel plugins listed above were added to the project by default, so the optional chaining is working even in vue components (except the <template> secion).
